# -*- coding: utf-8 -*-
"""build_ground_truth.py — Generates ground-truth indices from actual disk scan.
Zero-hardcode: every line is from a real scan. Exit 1 on failure."""
import json, re, sys, hashlib
from pathlib import Path
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

SCRIPT = Path(__file__).resolve()
DST = SCRIPT.parent.parent.parent            # canonical workspace root
sys.path.insert(0, str(DST))
OUT = DST / "ground-truth"
OUT.mkdir(parents=True, exist_ok=True)
def hdr(title, src, extra=""):
    return (f"# {title}\n> AUTO-GENERATED by build_ground_truth.py — DO NOT EDIT BY HAND\n"
            f"> Source: `{src}`{extra}\n\n")

def fam_of(n):
    n = n.lower()
    if n.startswith("logo-") or n in ("lower-third", "subscribe-reminder"): return "Branding & Logos"
    if any(k in n for k in ("chart", "stat", "progress", "counter", "comparison")): return "Data & Stats"
    if any(k in n for k in ("transition", "wipe", "dissolve", "whip", "morph", "iris", "blinds", "pixel", "fade", "zoom-through", "clock")): return "Transitions"
    if any(k in n for k in ("noise", "film", "bokeh", "gradient", "grid", "geometric", "liquid", "matrix", "starfield", "sound-wave", "particle", "camera-shake", "vignette")): return "VFX & Overlays"
    if any(k in n for k in ("picture", "card", "carousel", "gallery", "photo", "polaroid", "stack", "notification", "parallax", "zoom-reveal", "split", "masonry")): return "Containers & Cards"
    if any(k in n for k in ("countdown", "end-card", "ken-burns", "letterbox", "spotlight", "credits")): return "CTA & Engagement"
    if any(k in n for k in ("text", "title", "quote", "typewriter", "glitch", "bubble", "popping", "bounce", "pulsing", "highlight", "list", "chapter")): return "Typography & Captions"
    return "Unclassified"

# ── 1) TEMPLATE_CATALOG & TEMPLATE_INDEX ─────────────────────────────
templates_dir = DST / "remotion-app/src/templates"
engine_dir = DST / "remotion-app/src/engine"
(OUT / "collections").mkdir(parents=True, exist_ok=True)

catalog = []

registry_path = DST / "registry" / "template-registry.tsx"
if registry_path.exists():
    content = registry_path.read_text(encoding="utf-8")
    m = re.search(r"CANONICAL_TEMPLATE_REGISTRY(?:[\s\S]*?)=\s*\{([\s\S]*?)\n\};", content)
    if m:
        entries_str = m.group(1)
        parts = re.split(r'\n\s+"([a-zA-Z0-9_-]+)":\s*\{', "\n  " + entries_str)
        
        for i in range(1, len(parts), 2):
            key = parts[i]
            body = parts[i+1]
            
            status_m = re.search(r"status\s*:\s*['\"]([^'\"]+)['\"]", body)
            status = status_m.group(1) if status_m else "experimental"
            
            cat_m = re.search(r"category\s*:\s*['\"]([^'\"]+)['\"]", body)
            t_type = cat_m.group(1) if cat_m else "misc"
            if t_type == "composition": t_type = "scene"
            
            aspects_m = re.search(r"supported_aspects\s*:\s*\[([^\]]+)\]", body)
            supported_aspects = []
            if aspects_m:
                supported_aspects = [a.strip("'\" \n") for a in aspects_m.group(1).split(",")]
            else:
                supported_aspects = ["16:9", "9:16", "1:1"]
                
            comp_m = re.search(r"component\s*:\s*([a-zA-Z0-9_]+)", body)
            component = comp_m.group(1) if comp_m else ""
            
            rel_path = ""
            if component:
                imp_m = re.search(r"import\s*\{?\s*" + component + r"\s*\}?\s*from\s*['\"]([^'\"]+)['\"]", content)
                if imp_m:
                    rel_path = imp_m.group(1).lstrip(".").strip("/")
            
            t_family = "core"
            path_parts = rel_path.split("/")
            if len(path_parts) > 2:
                t_family = path_parts[2]
            
            # Simple heuristic for quality & source (same as before)
            quality = "C"
            source = "legacy"
            if "remocn" in rel_path:
                source = "remocn"
                quality = "A"
            elif "remotion-bits" in rel_path:
                source = "remotion-bits"
                quality = "A"
            elif "engine" in rel_path:
                source = "engine"
                quality = "A"
            elif "premium" in rel_path or "elements/" in rel_path or "scenes/" in rel_path:
                source = "premium"
                quality = "A"

            catalog.append({
                "id": key,
                "name": key.replace("-", " ").title().replace(" ", ""),
                "type": t_type,
                "family": t_family,
                "quality": quality,
                "status": status,
                "supported_aspects": supported_aspects,
                "rtl_ready": True if "typography" in rel_path or "captions" in rel_path else False,
                "source": source,
                "path": rel_path,
                "use_cases": [],
                "intents": [],
                "moods": [],
                "capabilities": [],
                "notes": ""
            })

# --- Classify Templates ---
sys.path.append(str(DST / "scripts"))
try:
    import classify_templates
    for item in catalog:
        f = item.get("family", "")
        n = item.get("name", "")
        p = item.get("path", "")
        t = item.get("type", "")
        q = item.get("quality", "C")
        s = item.get("source", "")
        
        item["use_cases"] = classify_templates.get_use_cases(f, n, p)
        item["intents"] = classify_templates.get_intents(f, n, t)
        item["moods"] = classify_templates.get_moods(f, n, q)
        item["capabilities"] = classify_templates.get_capabilities(f, n, s)
except ImportError:
    print("Warning: classify_templates not found, skipping classification.")





catalog_path = OUT / "template_catalog.json"
import json
catalog_path.write_text(json.dumps(catalog, indent=2, ensure_ascii=False), encoding="utf-8")

collections = {
    "ads": {"use_cases": ["ad"]},
    "explainers": {"use_cases": ["explainer", "education"]},
    "social": {"use_cases": ["social"]},
    "saas": {"use_cases": ["saas", "product"]},
    "product": {"use_cases": ["product", "launch"]}
}
for col_name, col_data in collections.items():
    uc = col_data['use_cases'][0]
    
    lines = [f"# {col_name.title()} Collection",
             "> Auto-Generated from template_catalog.json",
             f"> Last Updated: N/A", ""]
             
    for cat_name, type_filter in [("Scenes", "scene"), ("Elements", "element"), ("Effects", "effect")]:
        lines.extend([f"## {cat_name}", "| Name | Quality | Path | Intents |", "|---|---|---|---|"])
        
        found = False
        for item in catalog:
            if uc in item.get("use_cases", []) and item.get("type") == type_filter:
                intents_str = ", ".join(item.get("intents", []))
                lines.append(f"| `{item['name']}` | {item['quality']} | `{item['path']}` | {intents_str} |")
                found = True
        if not found:
            lines.append("| (None) | - | - | - |")
        lines.append("")
        
    (OUT / "collections" / f"{col_name}.md").write_text("\n".join(lines), encoding="utf-8")

lines = []
lines.append("| File | Type | Family | Source | Path |")
lines.append("|---|---|---|---|---|")
for c in catalog:
    lines.append(f"| `{c['name']}` | {c['type']} | {c['family']} | {c['source']} | `{c['path']}` |")

count = len(catalog)
import hashlib
(OUT / "TEMPLATE_INDEX.md").write_text(
    hdr("TEMPLATE_INDEX — Real templates on disk", "template_catalog.json", f" | SHA256: {hashlib.sha256(json.dumps(catalog).encode()).hexdigest()[:16]}")
    + f"**Count: {count} templates**\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
print(f"TEMPLATE_INDEX: {count}")

# ── 2) MCP_INDEX ──────────────────────────────────
out, servers = ["| Server | Tool | Signature |", "|---|---|---|"], 0
for srv in sorted((DST / ".agents/plugins/super-video-maker-plugin/tools/mcp-servers").iterdir()):
    if not srv.is_dir(): continue
    found = []
    for py in sorted(srv.rglob("*.py")):
        if any(p.startswith(".venv") or p == "site-packages" or p == "__pycache__" for p in py.parts):
            continue
        src = py.read_text(encoding="utf-8")
        for m in re.finditer(r"@\w+\.tool\(\)\s*\n\s*(?:async\s+)?def\s+(\w+)\s*\(([^)]*)\)", src):
            found.append((m.group(1), re.sub(r"\s+", " ", m.group(2).strip())))
    for js in sorted(srv.glob("*.js")) + sorted(srv.glob("*.ts")):
        if any(p == "node_modules" for p in js.parts):
            continue
        src = js.read_text(encoding="utf-8")
        for m in re.finditer(r"name:\s*['\"]([a-zA-Z0-9_-]+)['\"](?:.*?properties:\s*\{(.*?)\})?", src, re.S):
            tool_name = m.group(1)
            if tool_name == srv.name:
                continue
            props = ""
            if m.group(2):
                prop_names = re.findall(r"(\w+):\s*\{", m.group(2))
                props = ", ".join(prop_names)
            found.append((tool_name, props))
    if found:
        servers += 1
        out += [f"| `{srv.name}` | `{n}` | `({a})` |" for n, a in found]


(OUT / "MCP_INDEX.md").write_text(hdr("MCP_INDEX — Real MCP Tools", "tools/mcp-servers/*")
    + f"**Servers: {servers}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"MCP_INDEX: {servers}")

# ── 3) TOOLS_INDEX ────────────────────────────────
out, n = ["| Tool | Description (first docstring line) |", "|---|---|"], 0
tool_files = sorted(list((DST / ".agents/plugins/super-video-maker-plugin/tools").glob("*.py")) + [p for p in (DST / "scripts").glob("*.py") if p.name == "materialize_project.py"])
for py in tool_files:
    m = re.search(r'"""(.*?)"""', py.read_text(encoding="utf-8"), re.S)
    desc = m.group(1).strip().splitlines()[0] if m and m.group(1).strip() else "—"
    n += 1; out.append(f"| `{py.name}` | {desc} |")
(OUT / "TOOLS_INDEX.md").write_text(hdr("TOOLS_INDEX — Python Tools", ".agents/plugins/super-video-maker-plugin/tools/*.py + scripts/generators/materialize_project.py")
    + f"**Count: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"TOOLS_INDEX: {n}")

# ── 4) RECIPES_INDEX ──────────────────────────────
out, n = ["| Recipe | Name / Goal |", "|---|---|"], 0
for j in sorted((DST / "recipes").glob("*.json")):
    if j.name == "schema.json": continue
    try: data = json.loads(j.read_text(encoding="utf-8"))
    except Exception: data = {}
    name = data.get("name") or data.get("id") or j.stem
    desc = str(data.get("description") or data.get("goal") or "")[:140]
    n += 1; out.append(f"| `{j.stem}` | {name} — {desc} |")
(OUT / "RECIPES_INDEX.md").write_text(hdr("RECIPES_INDEX — Recipes", "recipes/*.json")
    + f"**Count: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"RECIPES_INDEX: {n}")

# ── 5) PLAYBOOKS_INDEX ────────────────────────────
out, n = ["| Document | Type | Title |", "|---|---|---|"], 0
guides_dir = DST / "docs" / "guides"
if guides_dir.exists():
    for md in sorted(guides_dir.glob("*.md")):
        first = next((l for l in md.read_text(encoding="utf-8").splitlines() if l.startswith("# ")), "# " + md.stem)
        n += 1; out.append(f"| `docs/guides/{md.name}` | Guide / Playbook | {first[2:].strip()} |")
reports_dir = DST / "docs" / "reports"
if reports_dir.exists():
    for md in sorted(reports_dir.glob("*.md")):
        first = next((l for l in md.read_text(encoding="utf-8").splitlines() if l.startswith("# ")), "# " + md.stem)
        n += 1; out.append(f"| `docs/reports/{md.name}` | Phase Report | {first[2:].strip()} |")
(OUT / "PLAYBOOKS_INDEX.md").write_text(hdr("PLAYBOOKS_INDEX — Playbooks, Guides, and Reports", "docs/guides/*.md, docs/reports/*.md")
    + f"**Count: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"PLAYBOOKS_INDEX: {n}")

# ── 6) CINEMATIC_INDEX ────────────────────────────
def cin_family(rel):
    rel = rel.lower()
    if rel.startswith("engine/audio"): return "Audio & Sync"
    if rel.startswith("engine/camera") or rel.startswith("engine/choreography"): return "Camera & Choreography"
    if rel.startswith("engine/cursor"): return "Cursor"
    if rel.startswith("engine/layout"): return "Layout & Zones"
    if rel.startswith("engine/ui-state"): return "UI State"
    if rel.startswith("primitives/app-ui"): return "App UI Mocks"
    if rel.startswith("primitives"): return "Primitives"
    if rel.startswith("scenes"): return "Scenes"
    return "Core"

lines, n = ["| File | Exports | Props (First 12) | Family |", "|---|---|---|---|"], 0
ce = DST / "remotion-app/src/engine"
if ce.exists():
    for f in sorted(list(ce.rglob("*.tsx")) + list(ce.rglob("*.ts"))):
        if f.name == "index.ts": continue
        src = f.read_text(encoding="utf-8")
        exp = re.findall(r"export\s+(?:const|function|class)\s+([A-Za-z_$][\w$]*)", src)
        exp += re.findall(r"export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)", src)
        mdef = re.search(r"export\s+default\s+([A-Za-z_$][\w$]*)", src)
        if mdef: exp.append(mdef.group(1) + " (default)")
        if not exp: continue
        props = []
        mpr = re.search(r"(?:type|interface)\s+\w*Props\w*\s*=\s*\{(.*?)\n\}", src, re.S)
        if mpr: props = re.findall(r"([A-Za-z_$][\w$]*)\s*[?]?:", mpr.group(1))
        n += 1
        rel = f.relative_to(ce).as_posix()
        lines.append(f"| `{rel}` | {', '.join(sorted(set(exp)))} | {', '.join(props[:12]) or '—'} | {cin_family(rel)} |")
(OUT / "CINEMATIC_INDEX.md").write_text(
    hdr("CINEMATIC_INDEX — Cinematic Engine components on disk", "engine/**/*.tsx|ts")
    + f"**Count: {n} components**\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
print(f"CINEMATIC_INDEX: {n}")

print("DONE — All indices generated from disk.")
