// هذا الملف تم توليده آلياً بواسطة docs-extractor.ts
// استخدمه كمرجع لبناء template-registry.tsx ولا تقم باستيراده مباشرة في الكود النهائي.

export const AUTO_GENERATED_TEMPLATES = [
  {
    id: "announce-title",
    props: [
      { name: "eyebrow", type: "string", description: "" },
      { name: "title", type: "string", description: "" },
      { name: "tagline", type: "string", description: "" },
      { name: "voidColor", type: "string", description: "" },
      { name: "fieldColor", type: "string", description: "" },
      { name: "paperColor", type: "string", description: "" },
      { name: "titleColor", type: "string", description: "" },
      { name: "nightColor", type: "string", description: "" },
      { name: "glowColor", type: "string", description: "" },
      { name: "glowStrength", type: "number", description: "" },
      { name: "taglineColor", type: "string", description: "" },
      { name: "symbolPath", type: "string", description: "" },
      { name: "symbolColors", type: "string[]", description: "ten measured stops" },
      { name: "symbolScale", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "answer-stream",
    props: [
      { name: "question", type: "string", description: "" },
      { name: "answer", type: "string", description: "" },
      { name: "headline", type: "string", description: "" },
      { name: "cards", type: "AnswerCard[]", description: "" },
      { name: "model", type: "string", description: "" },
      { name: "commitAt", type: "number", description: "" },
      { name: "cutAt", type: "number", description: "" },
      { name: "pullbackAt", type: "number", description: "" },
      { name: "pullbackDuration", type: "number", description: "" },
      { name: "wordsPerSecond", type: "number", description: "" },
      { name: "coolSeconds", type: "number", description: "" },
      { name: "macroZoom", type: "number", description: "" },
      { name: "blur", type: "number", description: "" },
      { name: "accentColor", type: "string", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "block-wordmark",
    props: [
      { name: "text", type: "string", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "fontFamily", type: "string", description: "" },
      { name: "fontWeight", type: "number", description: "700" },
      { name: "color", type: "string", description: "" },
      { name: "colors", type: "string[]", description: "deck colours" },
      { name: "blockSizing", type: "\"square\"", description: "\"square\"" },
      { name: "blockGap", type: "number", description: "" },
      { name: "cornerRadius", type: "number", description: "" },
      { name: "ascenderRatio", type: "number", description: "" },
      { name: "cards", type: "number", description: "" },
      { name: "spinTurns", type: "number", description: "" },
      { name: "growDuration", type: "number", description: "" },
      { name: "spinDuration", type: "number", description: "" },
      { name: "splitDuration", type: "number", description: "" },
      { name: "holdDuration", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "caret",
    props: [
      { name: "color", type: "string", description: "" },
      { name: "width", type: "number", description: "" },
      { name: "height", type: "number", description: "" },
      { name: "radius", type: "number", description: "" },
      { name: "opacity", type: "number", description: "" },
      { name: "blink", type: "boolean", description: "" },
      { name: "blinkPerSecond", type: "number", description: "" },
      { name: "marginLeft", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
      { name: "className", type: "string", description: "" },
      { name: "style", type: "CSSProperties", description: "" },
    ]
  },
  {
    id: "follower-rush",
    props: [
      { name: "totalFollowers", type: "number", description: "" },
      { name: "followers", type: "Follower[]", description: "" },
      { name: "accentColor", type: "string", description: "" },
      { name: "orientation", type: "\"horizontal\"", description: "\"horizontal\"" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "mode", type: "\"light\"", description: "—" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "hero-launch",
    props: [
      { name: "heading", type: "string", description: "" },
      { name: "image1", type: "string", description: "" },
      { name: "image2", type: "string", description: "" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
    ]
  },
  {
    id: "input",
    props: [
      { name: "state", type: "\"idle\"", description: "\"active\"" },
      { name: "style", type: "InputStyle", description: "" },
      { name: "placeholder", type: "string", description: "" },
      { name: "value", type: "string", description: "" },
      { name: "size", type: "InputSize", description: "" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "primary", type: "string", description: "" },
      { name: "fullWidth", type: "boolean", description: "" },
      { name: "className", type: "string", description: "" },
    ]
  },
  {
    id: "karaoke-captions",
    props: [
      { name: "captions", type: "Caption[]", description: "" },
      { name: "srt", type: "string", description: "" },
      { name: "lines", type: "CaptionLine[]", description: "" },
      { name: "text", type: "string", description: "" },
      { name: "emphasize", type: "string", description: "" },
      { name: "preset", type: "\"boxed\"", description: "\"highlight\"" },
      { name: "aspect", type: "\"landscape\"", description: "\"square\"`" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
      { name: "accentColor", type: "string", description: "" },
      { name: "emphasisScale", type: "number", description: "" },
      { name: "baseColor", type: "string", description: "" },
      { name: "fillColor", type: "string", description: "" },
      { name: "strokeRatio", type: "number", description: "" },
      { name: "pill", type: "boolean", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "laptop-frame",
    props: [
      { name: "children", type: "ReactNode", description: "" },
      { name: "screenSrc", type: "string", description: "" },
      { name: "entrance", type: "\"rise\"", description: "\"none\"`" },
      { name: "finale", type: "\"none\"", description: "\"none\"" },
      { name: "bezelColor", type: "string", description: "" },
      { name: "screenColor", type: "string", description: "" },
      { name: "indicatorColor", type: "string", description: "" },
      { name: "restTilt", type: "number", description: "" },
      { name: "radius", type: "number", description: "" },
      { name: "shadow", type: "string", description: "" },
      { name: "scale", type: "number", description: "" },
      { name: "showNotch", type: "boolean", description: "" },
      { name: "notchLabel", type: "string", description: "" },
      { name: "batteryLevel", type: "number", description: "" },
      { name: "floatLoop", type: "boolean", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "logo-assemble",
    props: [
      { name: "logoSrc", type: "string", description: "" },
      { name: "brandName", type: "string", description: "" },
      { name: "middleText", type: "string", description: "" },
      { name: "images", type: "string[]", description: "" },
      { name: "count", type: "number", description: "" },
      { name: "background", type: "string", description: "" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "logo-flicker",
    props: [
      { name: "logoSrc", type: "string", description: "" },
      { name: "brandName", type: "string", description: "" },
      { name: "images", type: "string[]", description: "" },
      { name: "flipInterval", type: "number", description: "" },
      { name: "background", type: "string", description: "" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "moodboard-reveal",
    props: [
      { name: "leadIn", type: "string", description: "" },
      { name: "emphasis", type: "string", description: "" },
      { name: "tailIn", type: "string", description: "" },
      { name: "images", type: "string[]", description: "" },
      { name: "heroImage", type: "string", description: "" },
      { name: "darkColor", type: "string", description: "" },
      { name: "lightColor", type: "string", description: "" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "orbit-gallery",
    props: [
      { name: "title", type: "string", description: "" },
      { name: "subtitle", type: "string", description: "" },
      { name: "buttonLabel", type: "string", description: "" },
      { name: "images", type: "string[]", description: "" },
      { name: "turns", type: "number", description: "" },
      { name: "spacing", type: "number", description: "" },
      { name: "spread", type: "number", description: "" },
      { name: "sizeAttenuation", type: "number", description: "" },
      { name: "imageSize", type: "number", description: "" },
      { name: "cardAspect", type: "number", description: "" },
      { name: "fadeIn", type: "number", description: "" },
      { name: "fadeOut", type: "number", description: "" },
      { name: "cornerRadius", type: "number", description: "" },
      { name: "orbitSeconds", type: "number", description: "" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
      { name: "footerLeft/Center/Right", type: "string", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "phone-frame",
    props: [
      { name: "children", type: "ReactNode", description: "" },
      { name: "screenSrc", type: "string", description: "" },
      { name: "variant", type: "\"flat\"", description: "\"showcase\"`" },
      { name: "entrance", type: "\"rise\"", description: "\"float\"`" },
      { name: "bezelColor", type: "string", description: "" },
      { name: "screenColor", type: "string", description: "" },
      { name: "radius", type: "number", description: "" },
      { name: "screenRadius", type: "number", description: "" },
      { name: "shadow", type: "string", description: "" },
      { name: "scale", type: "number", description: "" },
      { name: "showDynamicIsland", type: "boolean", description: "" },
      { name: "floatLoop", type: "boolean", description: "" },
      { name: "floatAmplitude", type: "number", description: "" },
      { name: "tiltAngle", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "prompt-zoom",
    props: [
      { name: "greeting", type: "string", description: "" },
      { name: "placeholder", type: "string", description: "" },
      { name: "text", type: "string", description: "" },
      { name: "chips", type: "string[]", description: "" },
      { name: "model", type: "string", description: "" },
      { name: "effort", type: "string", description: "" },
      { name: "typeStart", type: "number", description: "" },
      { name: "cutAt", type: "number", description: "" },
      { name: "charsPerSecond", type: "number", description: "" },
      { name: "zoom", type: "number", description: "" },
      { name: "focusX", type: "number", description: "" },
      { name: "focusY", type: "number", description: "" },
      { name: "accentColor", type: "string", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "pulsing-border",
    props: [
      { name: "glowColorA", type: "string", description: "" },
      { name: "glowColorB", type: "string", description: "" },
      { name: "roundness", type: "number", description: "" },
      { name: "thickness", type: "number", description: "" },
      { name: "intensity", type: "number", description: "" },
      { name: "bloom", type: "number", description: "" },
      { name: "colorBack", type: "string", description: "" },
      { name: "speed", type: "number", description: "" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "mode", type: "\"light\"", description: "—" },
    ]
  },
  {
    id: "search-typing",
    props: [
      { name: "text", type: "string", description: "" },
      { name: "charsPerSecond", type: "number", description: "" },
      { name: "humanize", type: "number", description: "" },
      { name: "wordPause", type: "number", description: "" },
      { name: "punctuationPause", type: "number", description: "" },
      { name: "startDelay", type: "number", description: "" },
      { name: "dollyDuration", type: "number", description: "" },
      { name: "panDuration", type: "number", description: "" },
      { name: "holdAfter", type: "number", description: "" },
      { name: "recedeDuration", type: "number", description: "" },
      { name: "dolly", type: "number", description: "" },
      { name: "fieldHeight", type: "number", description: "" },
      { name: "surface", type: "\"shadcn\"", description: "\"shadcn\"" },
      { name: "icon", type: "\"search\"", description: "\"none\"`" },
      { name: "caret", type: "boolean", description: "" },
      { name: "seed", type: "string", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "snap-cn-ui",
    props: [
      { name: "useSnapCnTheme(theme, mode)", type: "hook", description: "" },
      { name: "SnapCnTheme", type: "type", description: "" },
      { name: "mixOklch(a, b, t)", type: "fn", description: "" },
    ]
  },
  {
    id: "status-cycle",
    props: [
      { name: "prefix", type: "string", description: "" },
      { name: "statuses", type: "string[]", description: "[\"animating\",\"transitioning\",…]" },
      { name: "chips", type: "string[]", description: "component names" },
      { name: "fieldColor", type: "string", description: "" },
      { name: "pageColor", type: "string", description: "" },
      { name: "pillColor", type: "string", description: "" },
      { name: "chipFills", type: "string[]", description: "period-3 cycle from the theme" },
      { name: "fontWeight", type: "number", description: "" },
      { name: "chipFontWeight", type: "number", description: "" },
      { name: "pillRadius", type: "number", description: "" },
      { name: "statusHold", type: "number", description: "" },
      { name: "introFrames", type: "number", description: "" },
      { name: "chipStagger", type: "number", description: "" },
      { name: "startAt", type: "number", description: "" },
      { name: "motion", type: "Partial<StatusCycleMotion>", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "terminal-simulator",
    props: [
      { name: "lines", type: "TerminalLine[]", description: "" },
      { name: "intro", type: "string", description: "default headline (`*asterisks*` tint with the accent)" },
      { name: "command", type: "CommandSpec", description: "DEFAULT_COMMAND" },
      { name: "background", type: "string", description: "" },
      { name: "borderColor", type: "string", description: "" },
      { name: "mode", type: "\"light\"", description: "\"dark\"" },
      { name: "fontSize", type: "number", description: "" },
      { name: "charsPerFrame", type: "number", description: "" },
      { name: "chunkSize", type: "number", description: "" },
      { name: "zoom", type: "boolean", description: "false (`true` = 2.4x)" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "text-build",
    props: [
      { name: "text", type: "string", description: "" },
      { name: "axis", type: "\"x\"", description: "\"x\"" },
      { name: "entryOffset", type: "number", description: "" },
      { name: "gap", type: "number", description: "" },
      { name: "firstDuration", type: "number", description: "" },
      { name: "pushDuration", type: "number", description: "" },
      { name: "entryScale", type: "number", description: "" },
      { name: "entryBlur", type: "number", description: "" },
      { name: "reflowBlur", type: "number", description: "" },
      { name: "easing", type: "[number,number,number,number]", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "fontWeight", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "text-highlight",
    props: [
      { name: "before", type: "string", description: "" },
      { name: "highlight", type: "string", description: "" },
      { name: "after", type: "string", description: "" },
      { name: "preset", type: "\"logo-wipe\"", description: "\"color\"" },
      { name: "baseColor", type: "string", description: "" },
      { name: "accentColor", type: "string", description: "" },
      { name: "replaceWith", type: "string", description: "" },
      { name: "startAt", type: "number", description: "" },
      { name: "drawDuration", type: "number", description: "" },
      { name: "thickness", type: "number", description: "" },
      { name: "shineColor", type: "string", description: "" },
      { name: "logoSrc", type: "string", description: "" },
      { name: "logoScale", type: "number", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "fontWeight", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "text-reveal",
    props: [
      { name: "text", type: "string", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "color", type: "string", description: "" },
      { name: "fontWeight", type: "number", description: "600" },
      { name: "initialScale", type: "number", description: "" },
      { name: "introDuration", type: "number", description: "" },
      { name: "holdDuration", type: "number", description: "" },
      { name: "pushScale", type: "number", description: "" },
      { name: "recedeDuration", type: "number", description: "" },
      { name: "assembleDuration", type: "number", description: "" },
      { name: "wordDelay", type: "number", description: "" },
      { name: "wordStagger", type: "number", description: "" },
      { name: "wordDuration", type: "number", description: "" },
      { name: "wordPush", type: "number", description: "" },
      { name: "wordFade", type: "number", description: "" },
      { name: "letterSpacing", type: "string", description: "" },
      { name: "theme", type: "Partial<SnapCnTheme>", description: "" },
      { name: "mode", type: "\"light\"", description: "—" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "text-swap",
    props: [
      { name: "fromText", type: "string", description: "" },
      { name: "toText", type: "string", description: "" },
      { name: "transition", type: "\"fly-through\"", description: "\"crossfade\"" },
      { name: "unit", type: "\"word\"", description: "per transition" },
      { name: "exitDuration", type: "number", description: "" },
      { name: "enterDuration", type: "number", description: "" },
      { name: "exitStagger", type: "number", description: "" },
      { name: "enterStagger", type: "number", description: "" },
      { name: "overlap", type: "number", description: "" },
      { name: "microDelay", type: "number", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "fontWeight", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "text-swell",
    props: [
      { name: "text", type: "string", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "fontWeight", type: "number", description: "600" },
      { name: "introDuration", type: "number", description: "" },
      { name: "riseDistance", type: "number", description: "" },
      { name: "riseDuration", type: "number", description: "" },
      { name: "frontScale", type: "number", description: "" },
      { name: "approachDelay", type: "number", description: "" },
      { name: "approachDuration", type: "number", description: "" },
      { name: "wordDelay", type: "number", description: "" },
      { name: "wordStagger", type: "number", description: "" },
      { name: "wordPush", type: "number", description: "" },
      { name: "bounceWords", type: "number", description: "" },
      { name: "letterSwell", type: "number", description: "" },
      { name: "holdDuration", type: "number", description: "" },
      { name: "recedeDuration", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "word-captions",
    props: [
      { name: "captions", type: "Caption[]", description: "" },
      { name: "srt", type: "string", description: "" },
      { name: "words", type: "CaptionWord[]", description: "\"Stop losing hours to manual invoices\"" },
      { name: "preset", type: "\"boxed\"", description: "\"beast\"" },
      { name: "activeStyle", type: "\"pop\"", description: "\"color\"`" },
      { name: "aspect", type: "\"16:9\"", description: "\"9:16\"`" },
      { name: "maxWords", type: "number", description: "" },
      { name: "maxChars", type: "number", description: "" },
      { name: "pageBreakMs", type: "number", description: "" },
      { name: "strokeRatio", type: "number", description: "" },
      { name: "strokeColor", type: "string", description: "" },
      { name: "uppercase", type: "boolean", description: "" },
      { name: "accentColor", type: "string", description: "" },
      { name: "framesPerWord", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
  {
    id: "word-flip",
    props: [
      { name: "prefix", type: "string", description: "" },
      { name: "words", type: "string[]", description: "" },
      { name: "suffix", type: "string", description: "" },
      { name: "gradient", type: "string[]", description: "" },
      { name: "cps", type: "number", description: "" },
      { name: "typeStart", type: "number", description: "" },
      { name: "charFade", type: "number", description: "" },
      { name: "jitter", type: "number", description: "" },
      { name: "pause", type: "number", description: "" },
      { name: "cycle", type: "number", description: "" },
      { name: "exitDuration", type: "number", description: "" },
      { name: "enterDuration", type: "number", description: "" },
      { name: "overlap", type: "number", description: "" },
      { name: "caret", type: "boolean", description: "" },
      { name: "loop", type: "boolean", description: "" },
      { name: "perspective", type: "number", description: "" },
      { name: "fontFamily", type: "string", description: "" },
      { name: "fontSize", type: "number", description: "" },
      { name: "speed", type: "number", description: "" },
    ]
  },
];
