"""
ai/capabilities/definitions.py
==============================
Canonical domain capability definitions for S27 Media & Video Platform.

All 32 capabilities are provider-neutral, versioned, schema-bound,
and carry explicit execution, cache, privacy, and cost metadata.
"""

from __future__ import annotations

from typing import Dict, List
from ai.contracts.common import CapabilityType, ExecutionClass
from ai.capabilities.types import (
    CachePolicy,
    CapabilityDefinition,
    CapabilityPrivacyClass,
    ContractBindingRef,
    CostUnit,
)

CANONICAL_CAPABILITY_DEFINITIONS: List[CapabilityDefinition] = [
    # =========================================================================
    # 1. Core Language & Reasoning
    # =========================================================================
    CapabilityDefinition(
        id=CapabilityType.TEXT_GENERATION,
        version="1.0.0",
        description="Provider-neutral natural language text completion, scriptwriting, and copy generation",
        input_contract=ContractBindingRef(contract_id="ai.contracts.text_generation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.text_generation.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=True,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.REASONING,
        version="1.0.0",
        description="Deep step-by-step reasoning, deductive logic, and structured architectural assessment",
        input_contract=ContractBindingRef(contract_id="ai.contracts.reasoning.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.reasoning.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=True,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.PLANNING,
        version="1.0.0",
        description="Hierarchical task breakdown, video timeline orchestration, and execution DAG synthesis",
        input_contract=ContractBindingRef(contract_id="ai.contracts.planning.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.planning.output", version="1.0.0"),
        supports_batch=False,
        supports_streaming=False,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.SUMMARIZATION,
        version="1.0.0",
        description="Distillation and key information extraction from transcripts, documents, and video briefs",
        input_contract=ContractBindingRef(contract_id="ai.contracts.summarization.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.summarization.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.TRANSLATION,
        version="1.0.0",
        description="Cross-lingual text translation preserving pacing, tone, and formatting constraints",
        input_contract=ContractBindingRef(contract_id="ai.contracts.translation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.translation.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),

    # =========================================================================
    # 2. Representation & Retrieval
    # =========================================================================
    CapabilityDefinition(
        id=CapabilityType.EMBEDDING,
        version="1.0.0",
        description="Dense vector embedding synthesis for semantic search, vector indexing, and clustering",
        input_contract=ContractBindingRef(contract_id="ai.contracts.embedding.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.embedding.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text", "image", "audio"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.MULTIMODAL_EMBEDDING,
        version="1.0.0",
        description="Unified cross-modal embedding space bridging text, images, and audio representations",
        input_contract=ContractBindingRef(contract_id="ai.contracts.multimodal_embedding.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.multimodal_embedding.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.TOKENS,
        media_types=["text", "image", "audio", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),

    # =========================================================================
    # 3. Audio & Speech
    # =========================================================================
    CapabilityDefinition(
        id=CapabilityType.SPEECH_TO_TEXT,
        version="1.0.0",
        description="Automatic speech recognition (ASR) converting spoken audio into verbatim text transcripts",
        input_contract=ContractBindingRef(contract_id="ai.contracts.speech_to_text.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.speech_to_text.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=True,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.LANGUAGE_DETECTION,
        version="1.0.0",
        description="Automated detection of natural languages and dialects from audio or text samples",
        input_contract=ContractBindingRef(contract_id="ai.contracts.language_detection.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.language_detection.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio", "text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.DIARIZATION,
        version="1.0.0",
        description="Speaker diarization segmenting multi-speaker audio tracks by speaker identity",
        input_contract=ContractBindingRef(contract_id="ai.contracts.diarization.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.diarization.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.SPEECH_ALIGNMENT,
        version="1.0.0",
        description="Forced phoneme and word-level temporal alignment binding transcript to audio waveform",
        input_contract=ContractBindingRef(contract_id="ai.contracts.speech_alignment.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.speech_alignment.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio", "text"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.TEXT_TO_SPEECH,
        version="1.0.0",
        description="Neural voice synthesis converting written text into natural spoken voiceover audio",
        input_contract=ContractBindingRef(contract_id="ai.contracts.text_to_speech.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.text_to_speech.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=True,
        cache_policy=CachePolicy.DETERMINISTIC,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.CHARACTERS,
        media_types=["text", "audio"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.AUDIO_DENOISE,
        version="1.0.0",
        description="Acoustic background noise suppression, hum removal, and room tone subtraction",
        input_contract=ContractBindingRef(contract_id="ai.contracts.audio_denoise.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.audio_denoise.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.AUDIO_ENHANCE,
        version="1.0.0",
        description="Acoustic vocal presence enhancement, equalization, and broadcast dynamics mastering",
        input_contract=ContractBindingRef(contract_id="ai.contracts.audio_enhance.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.audio_enhance.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.VOCAL_ISOLATION,
        version="1.0.0",
        description="Acoustic source separation isolating vocal stems from background music and sound effects",
        input_contract=ContractBindingRef(contract_id="ai.contracts.vocal_isolation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.vocal_isolation.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.BEAT_DETECTION,
        version="1.0.0",
        description="Musical tempo, onset detection, and beat grid timestamp extraction for rhythmic cuts",
        input_contract=ContractBindingRef(contract_id="ai.contracts.beat_detection.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.beat_detection.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.MUSIC_GENERATION,
        version="1.0.0",
        description="Generative background music track synthesis conditioned on mood, tempo, and duration",
        input_contract=ContractBindingRef(contract_id="ai.contracts.music_generation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.music_generation.output", version="1.0.0"),
        supports_batch=False,
        supports_streaming=True,
        cache_policy=CachePolicy.NEVER,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.VOICE_ANALYSIS,
        version="1.0.0",
        description="Acoustic feature analysis measuring voice pitch, speaking rate, energy, and timbre",
        input_contract=ContractBindingRef(contract_id="ai.contracts.voice_analysis.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.voice_analysis.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.AUDIO_SECONDS,
        media_types=["audio"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),

    # =========================================================================
    # 4. Vision & Visual Understanding
    # =========================================================================
    CapabilityDefinition(
        id=CapabilityType.VISION,
        version="1.0.0",
        description="General multi-modal image inspection, visual question answering, and feature analysis",
        input_contract=ContractBindingRef(contract_id="ai.contracts.vision.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.vision.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.VIDEO_UNDERSTANDING,
        version="1.0.0",
        description="Temporal video reasoning, activity comprehension, and narrative arc extraction",
        input_contract=ContractBindingRef(contract_id="ai.contracts.video_understanding.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.video_understanding.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.VIDEO_SECONDS,
        media_types=["video"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.OCR,
        version="1.0.0",
        description="Optical character recognition extracting text, bounding coordinates, and font style",
        input_contract=ContractBindingRef(contract_id="ai.contracts.ocr.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.ocr.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.SHOT_DETECTION,
        version="1.0.0",
        description="Automated hard cut and soft transition boundary detection within video tracks",
        input_contract=ContractBindingRef(contract_id="ai.contracts.shot_detection.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.shot_detection.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.VIDEO_SECONDS,
        media_types=["video"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.OBJECT_DETECTION,
        version="1.0.0",
        description="Visual spatial object detection yielding labeled bounding boxes across video frames",
        input_contract=ContractBindingRef(contract_id="ai.contracts.object_detection.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.object_detection.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.FRAMES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.PERSON_DETECTION,
        version="1.0.0",
        description="Visual detection, tracking, and bounding box localization of human subjects",
        input_contract=ContractBindingRef(contract_id="ai.contracts.person_detection.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.person_detection.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.FRAMES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.SCENE_CLASSIFICATION,
        version="1.0.0",
        description="Semantic scene categorization (e.g. studio, urban, natural, indoor) for video b-roll matching",
        input_contract=ContractBindingRef(contract_id="ai.contracts.scene_classification.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.scene_classification.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.FRAMES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.CAPTIONING,
        version="1.0.0",
        description="Descriptive caption generation for visual frames and video clips",
        input_contract=ContractBindingRef(contract_id="ai.contracts.captioning.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.captioning.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),

    # =========================================================================
    # 5. Visual Synthesis & Manipulation
    # =========================================================================
    CapabilityDefinition(
        id=CapabilityType.IMAGE_GENERATION,
        version="1.0.0",
        description="Generative still image synthesis from text prompts and visual style conditioning",
        input_contract=ContractBindingRef(contract_id="ai.contracts.image_generation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.image_generation.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.NEVER,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.VIDEO_GENERATION,
        version="1.0.0",
        description="Generative video clip synthesis from text prompts, initial keyframes, or motion trajectories",
        input_contract=ContractBindingRef(contract_id="ai.contracts.video_generation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.video_generation.output", version="1.0.0"),
        supports_batch=False,
        supports_streaming=False,
        cache_policy=CachePolicy.NEVER,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.VIDEO_SECONDS,
        media_types=["video"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.PERSON_SEGMENTATION,
        version="1.0.0",
        description="Pixel-accurate matte and semantic segmentation mask generation for human figures",
        input_contract=ContractBindingRef(contract_id="ai.contracts.person_segmentation.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.person_segmentation.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.FRAMES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.BACKGROUND_REMOVAL,
        version="1.0.0",
        description="Automated alpha-channel background separation and transparency keying for media assets",
        input_contract=ContractBindingRef(contract_id="ai.contracts.background_removal.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.background_removal.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.INTERACTIVE,
    ),
    CapabilityDefinition(
        id=CapabilityType.LIP_SYNC,
        version="1.0.0",
        description="Audio-driven facial and lip geometry animation synchronizing avatar mouth motion to speech",
        input_contract=ContractBindingRef(contract_id="ai.contracts.lip_sync.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.lip_sync.output", version="1.0.0"),
        supports_batch=False,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        cost_unit=CostUnit.VIDEO_SECONDS,
        media_types=["video", "audio"],
        execution_tier=ExecutionClass.BATCH,
    ),
    CapabilityDefinition(
        id=CapabilityType.UPSCALE,
        version="1.0.0",
        description="Neural super-resolution spatial upscaling and detail reconstruction for image and video",
        input_contract=ContractBindingRef(contract_id="ai.contracts.upscale.input", version="1.0.0"),
        output_contract=ContractBindingRef(contract_id="ai.contracts.upscale.output", version="1.0.0"),
        supports_batch=True,
        supports_streaming=False,
        cache_policy=CachePolicy.CONTENT_HASH,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        cost_unit=CostUnit.IMAGES,
        media_types=["image", "video"],
        execution_tier=ExecutionClass.BATCH,
    ),
]

CANONICAL_CAPABILITY_MAP: Dict[CapabilityType, CapabilityDefinition] = {
    defn.id: defn for defn in CANONICAL_CAPABILITY_DEFINITIONS
}
