/* eslint-disable */
// ============================================================================
// GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate_ai_contracts.py from ai/contracts
// Single Authority: Python Pydantic Models (ai/contracts/*.py)
// ============================================================================

/** Generic JSON value representation strictly preventing unrestricted arbitrary objects. */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

/** ISO 8601 timezone-aware UTC datetime string (e.g. '2026-09-30T17:00:00Z'). */
export type TzAwareDatetime = string;

export type ExecutionClass = "INTERACTIVE" | "BATCH" | "BACKGROUND";

export type PrivacyRequirement = "ZERO_DATA_RETENTION" | "INTERNAL_ONLY" | "PUBLIC_ALLOWED";

export type QualityTarget = "DRAFT" | "STANDARD" | "HIGH" | "ULTRA";

export type CapabilityType = "TEXT_GENERATION" | "REASONING" | "PLANNING" | "SUMMARIZATION" | "TRANSLATION" | "EMBEDDING" | "MULTIMODAL_EMBEDDING" | "SPEECH_TO_TEXT" | "LANGUAGE_DETECTION" | "DIARIZATION" | "SPEECH_ALIGNMENT" | "TEXT_TO_SPEECH" | "AUDIO_DENOISE" | "AUDIO_ENHANCE" | "VOCAL_ISOLATION" | "BEAT_DETECTION" | "MUSIC_GENERATION" | "VOICE_ANALYSIS" | "VISION" | "VIDEO_UNDERSTANDING" | "OCR" | "SHOT_DETECTION" | "OBJECT_DETECTION" | "PERSON_DETECTION" | "SCENE_CLASSIFICATION" | "CAPTIONING" | "IMAGE_GENERATION" | "VIDEO_GENERATION" | "PERSON_SEGMENTATION" | "BACKGROUND_REMOVAL" | "LIP_SYNC" | "UPSCALE" | "TRIM_AUDIO" | "EXTEND_AUDIO" | "NORMALIZE_AUDIO_LOUDNESS" | "NORMALIZE_AUDIO" | "TRIM_AUDIO_SILENCE" | "ANALYZE_LOUDNESS" | "DETECT_SILENCE" | "SEGMENT_SPEECH_AUDIO" | "GENERATE_SPEECH_MANIFEST" | "BUILD_SPEECH_TIMELINE" | "SPLIT_SPEECH_TEXT" | "PREPARE_VO_SEGMENTS" | "ALIGN_AUDIO_METADATA" | "TRIM_VIDEO" | "EXTEND_VIDEO" | "RESIZE_VIDEO" | "TRIM_BLACK_FRAMES" | "CHANGE_VIDEO_SPEED" | "ENFORCE_KEYFRAME_INTERVAL" | "CONCATENATE_VIDEOS" | "PROBE_MEDIA" | "TRANSCODE_VIDEO" | "EXTRACT_AUDIO" | "EXTRACT_FRAMES" | "CONCAT_MEDIA" | "CHANGE_CONTAINER" | "NORMALIZE_MEDIA" | "RESIZE_IMAGE" | "CROP_IMAGE_TO_RATIO" | "AUTO_CROP_IMAGE" | "CONVERT_IMAGE" | "OPTIMIZE_IMAGE" | "PROBE_IMAGE" | "PREPARE_IMAGE_ASSET" | "THUMBNAIL" | "DOWNLOAD_REMOTE_MEDIA" | "EXTRACT_MEDIA_PAGE" | "SEARCH_ICONS" | "DOWNLOAD_ICON" | "SEARCH_STOCK_IMAGES" | "SEARCH_STOCK_VIDEOS" | "SEARCH_STOCK_AUDIO" | "SEARCH_SOUND_EFFECTS" | "INSPECT_MEDIA" | "MUTATE_ASSET_STATUS" | "CHECK_MEDIA_CACHE" | "STORE_MEDIA_CACHE" | "GET_JOB_STATUS" | "CANCEL_PROCESSING_JOB";

export type CapabilityStatus = "SUCCESS" | "FAILED" | "PARTIAL";

export type AIErrorCode = "PROVIDER_UNAVAILABLE" | "RATE_LIMITED" | "TIMEOUT" | "INVALID_MODEL_OUTPUT" | "SCHEMA_VALIDATION_FAILED" | "CAPABILITY_UNAVAILABLE" | "BUDGET_EXCEEDED" | "POLICY_DENIED" | "TENANT_ACCESS_DENIED" | "CONTENT_REJECTED" | "DEPENDENCY_FAILED" | "CANCELLED" | "INTERNAL_ERROR";

export type AIResponseStatus = "SUCCEEDED" | "FAILED" | "CANCELLED";

export type AIRunStatus = "PENDING" | "RUNNING" | "WAITING" | "SUCCEEDED" | "FAILED" | "CANCELLED";

export type AIStepStatus = "PENDING" | "RUNNING" | "WAITING" | "SUCCEEDED" | "FAILED" | "CANCELLED";

export type ToolCallStatus = "SUCCESS" | "ERROR";

export type MemoryType = "WORKING" | "CONVERSATION" | "PROJECT" | "USER_PREFERENCE" | "WORKSPACE" | "DECISION" | "KNOWLEDGE" | "MEDIA_INTELLIGENCE" | "EPISODIC" | "SEMANTIC";

export type ActivityStatus = "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";

export type IdempotencySemantics = "AT_MOST_ONCE" | "AT_LEAST_ONCE" | "EFFECTIVELY_ONCE";

export type CacheEntryStatus = "IN_FLIGHT" | "READY" | "FAILED";

export type PromptStatus = "DRAFT" | "TESTING" | "PRODUCTION" | "RETIRED";

export type SpanType = "AI_RUN" | "CONTEXT_BUILD" | "MEMORY_RETRIEVAL" | "MODEL_ROUTE" | "CACHE_LOOKUP" | "PROVIDER_CALL" | "TOOL_CALL" | "VALIDATION" | "ARTIFACT_PERSISTENCE";

export type CandidateType = "MODEL" | "PROMPT" | "ROUTER_POLICY";

export type EvaluatorType = "DETERMINISTIC" | "SCHEMA_BASED" | "CODE_BASED" | "HUMAN_LABEL" | "LLM_JUDGE";

export type ModelPromotionState = "CANDIDATE" | "OFFLINE_EVAL" | "COST_BENCHMARK" | "LATENCY_BENCHMARK" | "SHADOW_VALIDATION" | "APPROVED" | "REJECTED";

export type CapabilityCategory = "MODEL" | "TOOL" | "DOMAIN_SERVICE";

export type CapabilityFamily = "SPEECH_INTELLIGENCE" | "AUDIO_PROCESSING" | "VIDEO_PROCESSING" | "IMAGE_PROCESSING" | "MEDIA_ACQUISITION" | "MEDIA_INSPECTION" | "ASSET_DOMAIN_OPERATIONS" | "CACHE_MANAGEMENT" | "JOB_MANAGEMENT";

export type SideEffectClass = "NONE" | "READ_ONLY" | "LOCAL_TEMP_WRITE" | "PERSISTENT_WRITE" | "EXTERNAL_NETWORK" | "DOMAIN_MUTATION" | "SUBPROCESS" | "BACKGROUND_JOB";

export type TenantScope = "NONE" | "WORKSPACE" | "PROJECT" | "ASSET" | "SYSTEM";

export type ExecutionMode = "LOCAL" | "WORKER" | "REMOTE" | "MODEL" | "EXTERNAL_API" | "COMPATIBILITY_MCP";

export type CostClass = "NEGLIGIBLE" | "LOW" | "MEDIUM" | "HIGH" | "EXTERNAL_BILLED";

export type LatencyClass = "INTERACTIVE" | "SHORT" | "LONG_RUNNING" | "BACKGROUND";

export type RetryPolicy = "NEVER" | "SAFE_TRANSIENT" | "CONDITIONAL";

export type IdempotencyPolicy = "READ_ONLY" | "IDEMPOTENT" | "IDEMPOTENT_WITH_KEY" | "NON_IDEMPOTENT" | "CONDITIONAL";

export type ImplementationStatus = "WORKING" | "PARTIALLY_WORKING" | "BROKEN" | "UNVERIFIED";

export type MigrationStrategy = "PRESERVE_AS_IS" | "WRAP" | "REPAIR_THEN_WRAP" | "MOVE_TO_MODEL_SUBSYSTEM" | "MOVE_TO_DOMAIN_SERVICE" | "CONSOLIDATE" | "NATIVE_REIMPLEMENT" | "COMPATIBILITY_ONLY";

export type CapabilityLifecycleStatus = "ACTIVE" | "EXPERIMENTAL" | "DEPRECATED" | "PROPOSED";

export interface ProvenanceRecord {
  source: string;
  model_id?: string | null;
  provider_id?: string | null;
  timestamp: TzAwareDatetime;
  latency_ms?: number | null;
}

export interface UsageUnitRecord {
  unit_type: string;
  quantity: number | string;
}

export interface UsageRecord {
  input_tokens?: number | null;
  output_tokens?: number | null;
  total_tokens?: number | null;
  audio_seconds?: number | string | null;
  video_seconds?: number | string | null;
  image_count?: number | null;
  reported_units?: UsageUnitRecord[] | null;
}

export interface CostEstimate {
  estimated_cost: number | string;
  reserved_cost?: number | string | null;
  actual_cost?: number | string | null;
  currency?: string;
  pricing_version?: string | null;
}

export interface AIError {
  code: AIErrorCode;
  message: string;
  retryable: boolean;
  details?: Record<string, JsonValue> | null;
  dependency_reference?: string | null;
}

export interface ModelRequirement {
  capability: CapabilityType;
  quality_target?: QualityTarget;
  budget_constraint?: CostEstimate | null;
  max_latency_ms?: number | null;
  language?: string | null;
  privacy_requirement?: PrivacyRequirement;
  media_type?: string | null;
  required_features?: string[];
  execution_class?: ExecutionClass | null;
}

export interface ModelSelection {
  primary_model: string;
  fallback_candidates?: string[];
  reason_code: string;
  estimated_cost: CostEstimate;
}

export interface CapabilityRequest {
  request_id?: string;
  capability_id: CapabilityType;
  capability?: CapabilityType;
  capability_version?: string;
  workspace_id?: string | null;
  project_id?: string | null;
  actor_id?: string | null;
  tenant_context?: Record<string, JsonValue> | null;
  input?: Record<string, JsonValue>;
  input_data?: Record<string, JsonValue>;
  idempotency_key?: string | null;
  correlation_id?: string | null;
  requested_timeout?: number | null;
  metadata?: Record<string, JsonValue>;
  requirements?: ModelRequirement | null;
  contract_version?: string;
}

export interface CapabilityResult {
  request_id?: string | null;
  capability_id: CapabilityType;
  capability?: CapabilityType;
  status: CapabilityStatus;
  output?: Record<string, JsonValue> | null;
  output_data?: Record<string, JsonValue> | null;
  execution_metadata?: Record<string, JsonValue>;
  implementation_id?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  duration_ms?: number | null;
  confidence?: number | null;
  provenance?: ProvenanceRecord | null;
  usage?: UsageRecord;
  error?: AIError | null;
}

export interface ImplementationDescriptor {
  implementation_id: string;
  implementation_kind: string;
  current_status: ImplementationStatus;
  source: string;
  provider_or_engine: string;
  constraints?: string[];
  known_issues?: string[];
  legacy_storage_behavior?: string | null;
}

export interface CapabilityDefinition {
  capability_id: CapabilityType;
  version?: string;
  name: string;
  description: string;
  category: CapabilityCategory;
  family: CapabilityFamily;
  input_contract: string;
  output_contract: string;
  side_effects: SideEffectClass[];
  side_effect_class: SideEffectClass;
  target_storage_boundary?: string;
  required_permissions?: string[];
  tenant_scope?: TenantScope;
  execution_mode?: ExecutionMode;
  timeout_seconds?: number;
  retry_policy?: RetryPolicy;
  idempotency_policy?: IdempotencyPolicy;
  cost_class?: CostClass;
  latency_class?: LatencyClass;
  implementations?: ImplementationDescriptor[];
  status?: CapabilityLifecycleStatus;
  owner: string;
}

export interface AudioSegmentItem {
  segment_id: string;
  storage_key: string;
  start_seconds: number;
  end_seconds: number;
  text?: string | null;
}

export interface DownloadedAssetItem {
  asset_id: string;
  storage_key: string;
  source_url: string;
  content_type: string;
  file_size_bytes: number;
}

export interface StockMediaItem {
  media_id: string;
  media_type: string;
  title?: string | null;
  preview_url?: string | null;
  download_url?: string | null;
  width?: number | null;
  height?: number | null;
  duration_seconds?: number | null;
  license?: string | null;
}

export interface IconSearchResultItem {
  icon_name: string;
  collection: string;
  name: string;
  svg_preview?: string | null;
}

export interface SpeechToTextInput {
  project_id: string;
  audio_storage_key: string;
  language?: string | null;
  model_size?: string | null;
  detect_speakers?: boolean;
}

export interface SegmentSpeechInput {
  project_id: string;
  audio_storage_key: string;
  segments?: SpeechSegment[] | null;
  min_duration_seconds?: number;
  max_duration_seconds?: number;
}

export interface SegmentSpeechOutput {
  project_id: string;
  slices: AudioSegmentItem[];
  total_segments: number;
}

export interface SpeechManifestInput {
  project_id: string;
  audio_storage_key: string;
  manifest_version?: string;
}

export interface SpeechManifestOutput {
  project_id: string;
  manifest_storage_key: string;
  sentence_count: number;
  total_duration_seconds: number;
  words_count: number;
}

export interface SpeechTimelineInput {
  project_id: string;
  audio_storage_key: string;
  fps?: number;
}

export interface SpeechTimelineOutput {
  project_id: string;
  timeline_storage_key: string;
  total_frames: number;
  cue_points_count: number;
}

export interface SpeechTextSegmentItem {
  index: number;
  text: string;
  start_seconds?: number | null;
  end_seconds?: number | null;
  duration_seconds?: number | null;
  split_reason?: string;
  word_count: number;
}

export interface SplitSpeechTextInput {
  text: string;
  language?: string | null;
  min_sentence_duration?: number;
  max_sentence_duration?: number;
  silence_threshold?: number;
}

export interface SplitSpeechTextOutput {
  segments: SpeechTextSegmentItem[];
  total_segments: number;
  total_words: number;
  language?: string | null;
}

export interface PreparedVoSegmentItem {
  segment_id: string;
  index: number;
  text: string;
  estimated_duration_seconds: number;
  voice_id?: string | null;
  audio_mode?: string;
}

export interface PrepareVoSegmentsInput {
  project_id: string;
  text_segments: string[];
  voice_id?: string | null;
  audio_mode?: string;
  speaking_rate?: number;
}

export interface PrepareVoSegmentsOutput {
  project_id: string;
  segments: PreparedVoSegmentItem[];
  total_segments: number;
  total_estimated_duration_seconds: number;
  audio_mode: string;
}

export interface AlignedWordItem {
  word: string;
  start_seconds: number;
  end_seconds: number;
  duration_seconds: number;
  confidence?: number | null;
}

export interface AlignedSegmentItem {
  segment_id: string;
  index: number;
  text: string;
  start_seconds: number;
  end_seconds: number;
  duration_seconds: number;
  words: AlignedWordItem[];
}

export interface AlignAudioMetadataInput {
  project_id: string;
  audio_storage_key: string;
  transcript: string;
  words: AlignedWordItem[];
  audio_duration_seconds: number;
}

export interface AlignAudioMetadataOutput {
  project_id: string;
  segments: AlignedSegmentItem[];
  total_words: number;
  covered_duration_seconds: number;
  audio_duration_seconds: number;
  coverage_ratio: number;
  is_valid?: boolean;
}

export interface SilenceIntervalItem {
  start_seconds: number;
  end_seconds: number;
  duration_seconds: number;
}

export interface DetectSilenceInput {
  project_id: string;
  audio_storage_key: string;
  threshold_db?: number;
  min_silence_duration_seconds?: number;
}

export interface DetectSilenceOutput {
  project_id: string;
  audio_storage_key: string;
  silence_intervals: SilenceIntervalItem[];
  total_silence_duration_seconds: number;
  audio_duration_seconds: number;
  silence_ratio: number;
  threshold_used_db: number;
}

export interface AnalyzeLoudnessInput {
  project_id: string;
  audio_storage_key: string;
}

export interface AnalyzeLoudnessOutput {
  project_id: string;
  audio_storage_key: string;
  integrated_lufs: number;
  loudness_range: number;
  true_peak_db: number;
  threshold_db?: number | null;
  measurement_standard: string;
  duration_seconds: number;
}

export interface NormalizeAudioInput {
  project_id: string;
  audio_storage_key: string;
  target_lufs?: number;
  true_peak_db?: number;
  loudness_range?: number;
  sample_rate?: number;
}

export interface NormalizeAudioOutput {
  project_id: string;
  output_storage_key: string;
  target_lufs: number;
  measured_lufs: number;
  duration_seconds: number;
  file_size_bytes: number;
}

export interface TrimAudioInput {
  project_id: string;
  audio_storage_key: string;
  target_duration_seconds: number;
}

export interface TrimAudioOutput {
  project_id: string;
  output_storage_key: string;
  duration_seconds: number;
}

export interface ExtendAudioInput {
  project_id: string;
  audio_storage_key: string;
  target_duration_seconds: number;
  mode?: string;
  fade_duration_seconds?: number;
  auto_trim_silence?: boolean;
}

export interface ExtendAudioOutput {
  project_id: string;
  output_storage_key: string;
  duration_seconds: number;
  loop_count: number;
}

export interface NormalizeLoudnessInput {
  project_id: string;
  audio_storage_key: string;
  target_lufs?: number;
  peak_limit_db?: number;
}

export interface NormalizeLoudnessOutput {
  project_id: string;
  output_storage_key: string;
  measured_lufs: number;
  normalization_applied?: boolean;
}

export interface TrimSilenceInput {
  project_id: string;
  audio_storage_key: string;
  silence_threshold_db?: number;
  min_silence_duration_seconds?: number;
}

export interface TrimSilenceOutput {
  project_id: string;
  output_storage_key: string;
  original_duration_seconds: number;
  trimmed_duration_seconds: number;
  trimmed_start_seconds: number;
  trimmed_end_seconds: number;
}

export interface TrimVideoInput {
  project_id: string;
  video_storage_key: string;
  start_time_seconds?: number;
  duration_seconds: number;
}

export interface TrimVideoOutput {
  project_id: string;
  output_storage_key: string;
  duration_seconds: number;
}

export interface ExtendVideoInput {
  project_id: string;
  video_storage_key: string;
  target_duration_seconds: number;
  mode?: string;
}

export interface ExtendVideoOutput {
  project_id: string;
  output_storage_key: string;
  duration_seconds: number;
  loop_count: number;
}

export interface ResizeVideoInput {
  project_id: string;
  video_storage_key: string;
  target_width: number;
  target_height: number;
  mode?: string;
}

export interface ResizeVideoOutput {
  project_id: string;
  output_storage_key: string;
  width: number;
  height: number;
}

export interface DetectBlackFramesInput {
  project_id: string;
  video_storage_key: string;
  black_ratio_threshold?: number;
  black_pixel_threshold?: number;
}

export interface DetectBlackFramesOutput {
  project_id: string;
  output_storage_key: string;
  original_duration_seconds: number;
  trimmed_duration_seconds: number;
  black_segments_count: number;
}

export interface ChangeVideoSpeedInput {
  project_id: string;
  video_storage_key: string;
  speed_factor: number;
  run_in_background?: boolean;
}

export interface ChangeVideoSpeedOutput {
  project_id: string;
  output_storage_key?: string | null;
  job_id?: string | null;
  is_async?: boolean;
}

export interface EnforceKeyframesInput {
  project_id: string;
  video_storage_key: string;
  keyframe_interval?: number;
}

export interface EnforceKeyframesOutput {
  project_id: string;
  output_storage_key: string;
  keyframe_interval: number;
}

export interface ConcatenateVideosInput {
  project_id: string;
  video_storage_keys: string[];
  transition?: string | null;
}

export interface ConcatenateVideosOutput {
  project_id: string;
  output_storage_key: string;
  total_duration_seconds: number;
  input_count: number;
}

export interface UpscaleImageInput {
  project_id: string;
  image_storage_key: string;
  scale_factor?: number;
  target_width?: number | null;
  target_height?: number | null;
}

export interface UpscaleImageOutput {
  project_id: string;
  output_storage_key: string;
  width: number;
  height: number;
}

export interface CropRatioInput {
  project_id: string;
  image_storage_key: string;
  aspect_ratio?: string;
}

export interface CropRatioOutput {
  project_id: string;
  output_storage_key: string;
  width: number;
  height: number;
  aspect_ratio: string;
}

export interface AutoCropInput {
  project_id: string;
  image_storage_key: string;
  padding_ratio?: number;
}

export interface AutoCropOutput {
  project_id: string;
  output_storage_key: string;
  cropped_box: number[];
  original_width: number;
  original_height: number;
  output_width: number;
  output_height: number;
}

export interface DownloadRemoteMediaInput {
  project_id: string;
  url: string;
  media_type?: string;
  destination_asset_id?: string | null;
}

export interface DownloadRemoteMediaOutput {
  project_id: string;
  asset_id: string;
  storage_key: string;
  file_size_bytes: number;
  content_type: string;
}

export interface ExtractMediaPageInput {
  project_id: string;
  page_url: string;
  media_type?: string;
}

export interface ExtractMediaPageOutput {
  project_id: string;
  extracted_assets: DownloadedAssetItem[];
  total_extracted: number;
}

export interface SearchIconsInput {
  query: string;
  limit?: number;
  collection?: string | null;
}

export interface SearchIconsOutput {
  query: string;
  icons: IconSearchResultItem[];
  total_found: number;
}

export interface DownloadIconInput {
  project_id: string;
  icon_name: string;
  color?: string | null;
  size?: number;
}

export interface DownloadIconOutput {
  project_id: string;
  asset_id: string;
  storage_key: string;
  format?: string;
}

export interface SearchStockImagesInput {
  query: string;
  page?: number;
  per_page?: number;
  orientation?: string | null;
}

export interface SearchStockImagesOutput {
  query: string;
  images: StockMediaItem[];
  page: number;
  total_results: number;
}

export interface SearchStockVideosInput {
  query: string;
  page?: number;
  per_page?: number;
  orientation?: string | null;
}

export interface SearchStockVideosOutput {
  query: string;
  videos: StockMediaItem[];
  page: number;
  total_results: number;
}

export interface SearchStockAudioInput {
  query: string;
  page?: number;
  per_page?: number;
}

export interface SearchStockAudioOutput {
  query: string;
  audio_tracks: StockMediaItem[];
  page: number;
  total_results: number;
}

export interface SearchSoundEffectsInput {
  query: string;
  page?: number;
  per_page?: number;
  duration_range?: number[] | null;
}

export interface SearchSoundEffectsOutput {
  query: string;
  sound_effects: StockMediaItem[];
  page: number;
  total_results: number;
}

export interface InspectMediaInput {
  project_id: string;
  storage_keys: string[];
}

export interface InspectMediaOutput {
  project_id: string;
  files_info: TechnicalMetadata[];
}

export interface MutateAssetStatusInput {
  project_id: string;
  asset_id: string;
  new_status: string;
  reason?: string | null;
}

export interface MutateAssetStatusOutput {
  project_id: string;
  asset_id: string;
  previous_status: string;
  current_status: string;
  manifest_updated?: boolean;
}

export interface CheckCacheInput {
  project_id: string;
  asset_id: string;
  transformation_hash: string;
}

export interface CheckCacheOutput {
  project_id: string;
  asset_id: string;
  transformation_hash: string;
  cache_hit: boolean;
  cached_storage_key?: string | null;
}

export interface StoreCacheInput {
  project_id: string;
  asset_id: string;
  transformation_hash: string;
  source_storage_key: string;
}

export interface StoreCacheOutput {
  project_id: string;
  asset_id: string;
  transformation_hash: string;
  cached_storage_key: string;
  stored?: boolean;
}

export interface GetJobStatusInput {
  project_id: string;
  job_id: string;
}

export interface GetJobStatusOutput {
  project_id: string;
  job_id: string;
  status: string;
  progress_percent?: number;
  output_storage_key?: string | null;
  error?: string | null;
}

export interface CancelJobInput {
  project_id: string;
  job_id: string;
  reason?: string | null;
}

export interface CancelJobOutput {
  project_id: string;
  job_id: string;
  cancelled: boolean;
  termination_status: string;
}

export interface ToolCall {
  call_id: string;
  tool_name: string;
  parameters?: Record<string, JsonValue>;
  untrusted_metadata?: Record<string, JsonValue> | null;
}

export interface ToolResult {
  call_id: string;
  status: ToolCallStatus;
  output?: Record<string, JsonValue> | null;
  error?: AIError | null;
  started_at: TzAwareDatetime;
  completed_at: TzAwareDatetime;
  duration_ms: number;
}

export interface MemoryQuery {
  workspace_id: string;
  project_id?: string | null;
  session_id?: string | null;
  memory_type: MemoryType;
  query_text: string;
  limit?: number;
  minimum_confidence?: number;
}

export interface MemoryEntry {
  entry_id: string;
  memory_type: MemoryType;
  content: string;
  relevance_score: number;
  confidence: number;
  provenance: ProvenanceRecord;
  created_at: TzAwareDatetime;
}

export interface MemoryResult {
  entries?: MemoryEntry[];
  total_found: number;
  query_duration_ms: number;
}

export interface MediaIntelligenceRef {
  artifact_id: string;
  asset_id: string;
  analysis_version?: string;
  content_hash: string;
  storage_key: string;
  created_at: TzAwareDatetime;
}

export interface AnalysisProvenance {
  producer: string;
  provider?: string | null;
  model?: string | null;
  version?: string | null;
  confidence?: number | null;
  timestamp: TzAwareDatetime;
  analysis_version?: string;
  contract_version?: string;
}

export interface TechnicalMetadata {
  format?: string | null;
  duration_seconds?: number | null;
  file_size_bytes?: number | null;
  has_audio: boolean;
  has_video: boolean;
  audio_channels?: number | null;
  audio_sample_rate?: number | null;
  audio_bitrate?: number | null;
  audio_codec?: string | null;
  width?: number | null;
  height?: number | null;
  fps?: number | null;
  video_codec?: string | null;
  provenance?: AnalysisProvenance | null;
}

export interface SpeechWord {
  text: string;
  start: number;
  end: number;
  speaker_id?: string | null;
  confidence?: number | null;
  language?: string | null;
}

export interface SpeechSegment {
  id?: string | null;
  start: number;
  end: number;
  text: string;
  speaker_id?: string | null;
  confidence?: number | null;
  language?: string | null;
  words?: SpeechWord[];
}

export interface SpeechSpeaker {
  speaker_id: string;
  label?: string | null;
  confidence?: number | null;
  total_speaking_time_seconds?: number | null;
}

export interface SpeechQuality {
  speech_snr_db?: number | null;
  audio_clarity_score?: number | null;
  clipping_detected?: boolean | null;
  silence_percentage?: number | null;
}

export interface SpeechIntelligence {
  language?: string | null;
  language_confidence?: number | null;
  transcript: string;
  segments?: SpeechSegment[];
  words?: SpeechWord[];
  speakers?: SpeechSpeaker[];
  duration_seconds?: number | null;
  overall_confidence?: number | null;
  provenance: AnalysisProvenance;
}

export interface BoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface VideoShot {
  shot_id: string;
  start: number;
  end: number;
  duration: number;
  confidence?: number | null;
  source?: string;
  transition_type?: string | null;
  keyframe_indices?: number[];
  provenance?: AnalysisProvenance | null;
}

export interface Keyframe {
  keyframe_id: string;
  shot_id?: string | null;
  timestamp: number;
  frame_index: number;
  storage_key?: string | null;
  width?: number | null;
  height?: number | null;
  is_representative?: boolean;
  resolution_tier?: string;
  content_hash?: string | null;
  provenance?: AnalysisProvenance | null;
}

export interface VisualOCRObservation {
  text: string;
  bounding_box?: BoundingBox | null;
  timestamp: number;
  frame_ref?: string | null;
  confidence: number;
  language?: string | null;
  is_ui_screen?: boolean;
  provenance: AnalysisProvenance;
}

export interface VisualObjectObservation {
  label: string;
  bounding_box?: BoundingBox | null;
  timestamp: number;
  frame_ref?: string | null;
  confidence: number;
  provenance: AnalysisProvenance;
}

export interface VisualPersonObservation {
  person_id: string;
  bounding_box?: BoundingBox | null;
  timestamp: number;
  frame_ref?: string | null;
  confidence: number;
  provenance: AnalysisProvenance;
}

export interface VisualSceneClassification {
  label: string;
  start: number;
  end: number;
  confidence: number;
  resolution_tier?: string;
  provenance: AnalysisProvenance;
}

export interface VisualObservation {
  summary: string;
  start: number;
  end: number;
  importance_score?: number | null;
  category?: string | null;
  provenance: AnalysisProvenance;
}

export interface VisualIntelligence {
  status?: string;
  has_visual_analysis?: boolean;
  shots?: VideoShot[];
  keyframes?: Keyframe[];
  ocr?: VisualOCRObservation[];
  objects?: VisualObjectObservation[];
  people?: VisualPersonObservation[];
  scene_classifications?: VisualSceneClassification[];
  observations?: VisualObservation[];
  provenance?: AnalysisProvenance | null;
}

export type VisualIntelligenceFoundation = VisualIntelligence;

export interface TimeRange {
  start: number;
  end: number;
  confidence?: number | null;
  label?: string | null;
}

export interface AudioLoudnessMetrics {
  integrated_lufs?: number | null;
  momentary_max_lufs?: number | null;
  rms_db?: number | null;
  peak_db?: number | null;
  clipping_detected?: boolean;
  clipping_events_count?: number;
  provenance?: AnalysisProvenance | null;
}

export interface AudioNoiseEstimate {
  snr_db?: number | null;
  noise_floor_db?: number | null;
  noise_profile_label?: string | null;
  confidence?: number | null;
  provenance?: AnalysisProvenance | null;
}

export interface AudioBeatTrack {
  tempo_bpm?: number | null;
  beat_timestamps?: number[];
  confidence?: number | null;
  provenance?: AnalysisProvenance | null;
}

export interface AudioQualityObservation {
  metric_name: string;
  score: number;
  details?: string | null;
  provenance?: AnalysisProvenance | null;
}

export interface AudioIntelligence {
  status?: string;
  has_audio_analysis?: boolean;
  speech_ranges?: TimeRange[];
  silence_ranges?: TimeRange[];
  loudness?: AudioLoudnessMetrics | null;
  noise_estimate?: AudioNoiseEstimate | null;
  beats?: AudioBeatTrack | null;
  music_ranges?: TimeRange[];
  quality_observations?: AudioQualityObservation[];
  noise_profile?: string | null;
  tempo_bpm?: number | null;
  beat_timestamps?: number[];
  vocal_isolation_ref?: string | null;
  provenance?: AnalysisProvenance | null;
}

export type AudioIntelligenceFoundation = AudioIntelligence;

// Specialized Media AI Operations
export interface TTSRequest {
  text: string;
  voice_id: string;
  language?: string | null;
  speed?: number | null;
  pitch?: number | null;
  format?: string;
}

export interface TTSResult {
  audio_storage_key: string;
  audio_hash: string;
  duration_seconds: number;
  sample_rate: number;
  format?: string;
  provenance: AnalysisProvenance;
}

export interface ImageGenerationRequest {
  prompt: string;
  negative_prompt?: string | null;
  width?: number;
  height?: number;
  style?: string | null;
  seed?: number | null;
}

export interface ImageGenerationResult {
  image_storage_key: string;
  image_hash: string;
  width: number;
  height: number;
  format?: string;
  provenance: AnalysisProvenance;
}

export interface VideoGenerationRequest {
  prompt: string;
  duration_seconds?: number;
  fps?: number;
  width?: number;
  height?: number;
  input_frame_storage_key?: string | null;
  seed?: number | null;
}

export interface VideoGenerationResult {
  video_storage_key: string;
  video_hash: string;
  duration_seconds: number;
  fps: number;
  width: number;
  height: number;
  format?: string;
  provenance: AnalysisProvenance;
}

export interface PersonSegmentationRequest {
  image_storage_key: string;
  content_hash: string;
  return_mask?: boolean;
  threshold?: number;
}

export interface PersonSegmentationResult {
  mask_storage_key: string;
  mask_hash: string;
  person_count?: number;
  confidence: number;
  provenance: AnalysisProvenance;
}

export interface BackgroundRemovalRequest {
  image_storage_key: string;
  content_hash: string;
  output_format?: string;
}

export interface BackgroundRemovalResult {
  output_storage_key: string;
  output_hash: string;
  format?: string;
  provenance: AnalysisProvenance;
}

export interface LipSyncRequest {
  video_storage_key: string;
  audio_storage_key: string;
  content_hash: string;
}

export interface LipSyncResult {
  output_video_storage_key: string;
  output_video_hash: string;
  duration_seconds: number;
  sync_confidence: number;
  provenance: AnalysisProvenance;
}

export interface UpscaleRequest {
  media_storage_key: string;
  content_hash: string;
  scale_factor?: number;
  target_width?: number | null;
  target_height?: number | null;
}

export interface UpscaleResult {
  output_storage_key: string;
  output_hash: string;
  width: number;
  height: number;
  provenance: AnalysisProvenance;
}

export interface AudioDenoiseRequest {
  audio_storage_key: string;
  content_hash: string;
  aggressiveness?: number;
}

export interface AudioDenoiseResult {
  output_audio_storage_key: string;
  output_audio_hash: string;
  noise_reduction_db?: number;
  provenance: AnalysisProvenance;
}

export interface AudioEnhanceRequest {
  audio_storage_key: string;
  content_hash: string;
  target_lufs?: number;
}

export interface AudioEnhanceResult {
  output_audio_storage_key: string;
  output_audio_hash: string;
  applied_lufs: number;
  provenance: AnalysisProvenance;
}

export interface VocalIsolationRequest {
  audio_storage_key: string;
  content_hash: string;
  extract_instrumental?: boolean;
}

export interface VocalIsolationResult {
  vocals_storage_key: string;
  vocals_hash: string;
  instrumental_storage_key?: string | null;
  instrumental_hash?: string | null;
  provenance: AnalysisProvenance;
}

export interface SemanticIntelligenceFoundation {
  status?: string;
  topics?: string[];
  summary?: string | null;
}

export interface MediaQualityIntelligence {
  speech?: SpeechQuality | null;
  audio_quality_score?: number | null;
  visual_quality_score?: number | null;
  overall_score?: number | null;
}

export interface MediaIntelligence {
  workspace_id: string;
  asset_id: string;
  content_hash: string;
  analysis_version?: string;
  contract_version?: string;
  created_at: TzAwareDatetime;
  technical?: TechnicalMetadata;
  speech?: SpeechIntelligence | null;
  audio?: AudioIntelligence;
  visual?: VisualIntelligence;
  semantic?: SemanticIntelligenceFoundation;
  quality?: MediaQualityIntelligence;
  provenance: AnalysisProvenance;
}

export interface AIRequest {
  request_id: string;
  workspace_id: string;
  actor_id: string;
  project_id?: string | null;
  session_id?: string | null;
  capability: CapabilityType;
  intent?: string | null;
  input_data?: Record<string, JsonValue>;
  quality_target?: QualityTarget;
  privacy_requirement?: PrivacyRequirement;
  execution_class?: ExecutionClass;
  metadata?: Record<string, JsonValue>;
  created_at: TzAwareDatetime;
  contract_version?: string;
}

export interface AIResponse {
  request_id: string;
  run_id?: string | null;
  status: AIResponseStatus;
  result?: Record<string, JsonValue> | null;
  usage?: UsageRecord;
  cost: CostEstimate;
  warnings?: string[];
  error?: AIError | null;
  created_at: TzAwareDatetime;
  contract_version?: string;
}

export interface AIRun {
  run_id: string;
  workspace_id: string;
  project_id?: string | null;
  session_id?: string | null;
  status: AIRunStatus;
  capability: CapabilityType;
  workflow_ref?: string | null;
  created_at: TzAwareDatetime;
  started_at?: TzAwareDatetime | null;
  completed_at?: TzAwareDatetime | null;
  usage?: UsageRecord;
  cost: CostEstimate;
  error?: AIError | null;
  contract_version?: string;
  execution_class?: ExecutionClass;
  prompt_id?: string | null;
  prompt_version?: string | null;
  prompt_hash?: string | null;
}

export interface AIStep {
  step_id: string;
  run_id: string;
  status: AIStepStatus;
  attempt?: number;
  capability: CapabilityType;
  input_ref?: string | null;
  output_ref?: string | null;
  provider?: string | null;
  model?: string | null;
  usage?: UsageRecord;
  cost: CostEstimate;
  error?: AIError | null;
  created_at: TzAwareDatetime;
  started_at?: TzAwareDatetime | null;
  completed_at?: TzAwareDatetime | null;
  prompt_id?: string | null;
  prompt_version?: string | null;
  prompt_hash?: string | null;
  worker_id?: string | null;
  lease_token?: string | null;
  lease_expires_at?: TzAwareDatetime | null;
  heartbeat_at?: TzAwareDatetime | null;
  input_hash?: string | null;
  idempotency_key?: string | null;
  dependencies?: string[];
  max_attempts?: number;
  next_retry_at?: TzAwareDatetime | null;
}

export interface AIActivityRecord {
  activity_id: string;
  run_id: string;
  step_id: string;
  idempotency_key: string;
  status: ActivityStatus;
  semantics?: IdempotencySemantics;
  started_at?: TzAwareDatetime | null;
  completed_at?: TzAwareDatetime | null;
  provider?: string | null;
  model?: string | null;
  remote_operation_ref?: string | null;
  output_ref?: string | null;
  error?: AIError | null;
  cost?: CostEstimate | null;
  usage?: UsageRecord | null;
  cost_settled?: boolean;
  reservation_id?: string | null;
  created_at: TzAwareDatetime;
}

export interface AICacheEntry {
  cache_key: string;
  workspace_id: string;
  capability: CapabilityType;
  input_hash: string;
  status: CacheEntryStatus;
  output_ref?: string | null;
  producer?: string | null;
  model?: string | null;
  model_version?: string | null;
  contract_version?: string;
  prompt_version?: string;
  analysis_version?: string;
  created_at: TzAwareDatetime;
  expires_at?: TzAwareDatetime | null;
  owner_id?: string | null;
  lease_token?: string | null;
  lease_expires_at?: TzAwareDatetime | null;
  activity_id?: string | null;
  activity_idempotency_key?: string | null;
  generation?: number;
  error?: AIError | null;
}

export interface PromptMetadata {
  author?: string | null;
  description?: string | null;
  tags?: string[];
  eval_gate_id?: string | null;
  eval_quality_score?: number | null;
}

export interface PromptContract {
  prompt_id: string;
  version: number;
  hash: string;
  status: PromptStatus;
  template: string;
  system_prompt?: string | null;
  variables?: string[];
  created_at: TzAwareDatetime;
  workspace_id?: string | null;
  metadata?: PromptMetadata;
}

export interface PromptRenderRequest {
  prompt_id: string;
  version?: number | null;
  variables?: Record<string, JsonValue>;
  workspace_id?: string | null;
}

export interface PromptRenderResult {
  prompt_id: string;
  version: number;
  hash: string;
  rendered_text: string;
  system_prompt?: string | null;
  status: PromptStatus;
}

export interface TraceSpanRecord {
  trace_id: string;
  span_id: string;
  parent_span_id?: string | null;
  span_type: SpanType;
  name: string;
  run_id: string;
  step_id?: string | null;
  activity_id?: string | null;
  workspace_id: string;
  project_id?: string | null;
  capability?: string | null;
  provider?: string | null;
  model?: string | null;
  prompt_id?: string | null;
  prompt_version?: string | null;
  started_at: TzAwareDatetime;
  ended_at?: TzAwareDatetime | null;
  duration_ms?: number | null;
  input_tokens?: number | null;
  output_tokens?: number | null;
  cache_hit?: boolean | null;
  retry_count?: number;
  fallback?: boolean;
  estimated_cost?: number | string | null;
  actual_cost?: number | string | null;
  quality_score?: number | null;
  status?: string;
  error_code?: string | null;
  attributes?: Record<string, JsonValue>;
}

export interface AITrace {
  trace_id: string;
  run_id: string;
  workspace_id: string;
  spans?: TraceSpanRecord[];
}

export interface EvalExample {
  example_id: string;
  input_payload: Record<string, JsonValue>;
  expected_output?: Record<string, JsonValue> | null;
  expected_schema?: string | null;
  ground_truth_label?: string | null;
  is_human_verified?: boolean;
  min_quality_score?: number;
}

export interface EvalDatasetContract {
  dataset_id: string;
  version: string;
  content_hash: string;
  capability: CapabilityType;
  description: string;
  examples: EvalExample[];
}

export interface EvalResultContract {
  evaluation_id: string;
  dataset_id: string;
  dataset_version: string;
  candidate_type: CandidateType;
  candidate_id: string;
  candidate_version: string;
  passed: boolean;
  quality_score: number;
  cost_score: number;
  latency_ms: number;
  evaluators_used: EvaluatorType[];
  created_at: TzAwareDatetime;
  failure_reasons?: string[];
  metrics?: Record<string, JsonValue>;
}

export interface BenchmarkDebtContract {
  benchmark_id: string;
  name: string;
  status?: string;
  target_stage?: string;
  fake_scores_injected?: boolean;
  notes: string;
}
