/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProjectId = string;
export type CurrentStage = number;
export type LastError = string | null;
export type StageStatus = "pending" | "running" | "done" | "failed";
export type StartedAt = string | null;
export type FinishedAt = string | null;
export type GateStatus = "locked" | "awaiting" | "approved" | "rejected";
export type ApprovedBy = string | null;
export type ApprovedAt = string | null;
export type Note = string | null;
export type UpdatedAt = string;
export type RunId = string | null;
export type CheckpointStage =
  | "INITIALIZED"
  | "ASSETS_READY"
  | "PLAN_READY"
  | "BLUEPRINT_READY"
  | "PROBE_READY"
  | "APPROVED"
  | "RENDERED"
  | "QC_PASSED"
  | "COMPLETE";
export type Path = string;
export type ValidationLevel = "EXISTS" | "SIZE" | "SHA256";
export type SizeBytes = number | null;
export type Sha256 = string | null;
export type ArtifactReferences = ArtifactRecord[];

export interface ProjectState {
  project_id: ProjectId;
  current_stage?: CurrentStage;
  last_error?: LastError;
  stages?: Stages;
  gates?: Gates;
  updated_at?: UpdatedAt;
  run_id?: RunId;
  checkpoint?: CheckpointStage;
  artifact_references?: ArtifactReferences;
  [k: string]: unknown;
}
export interface Stages {
  [k: string]: StageEntry;
}
export interface StageEntry {
  status?: StageStatus;
  started_at?: StartedAt;
  finished_at?: FinishedAt;
  [k: string]: unknown;
}
export interface Gates {
  [k: string]: GateEntry;
}
export interface GateEntry {
  status?: GateStatus;
  approved_by?: ApprovedBy;
  approved_at?: ApprovedAt;
  note?: Note;
  [k: string]: unknown;
}
export interface ArtifactRecord {
  path: Path;
  validation: ValidationLevel;
  size_bytes?: SizeBytes;
  sha256?: Sha256;
  [k: string]: unknown;
}
