/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProjectId = string;
export type SchemaVersion = number;
export type Revision = number;
export type LifecycleState =
  | "DRAFT"
  | "ASSETS_READY"
  | "PLAN_READY"
  | "BLUEPRINT_READY"
  | "MATERIALIZED"
  | "PROBE_PASSED"
  | "AWAITING_REVIEW"
  | "REVIEW_APPROVED"
  | "RENDERED"
  | "FINAL_QC_PASSED"
  | "COMPLETE"
  | "FAILED"
  | "CANCELLED";
export type StructuredErrors = {
  [k: string]: unknown;
}[];
export type Path = string;
export type ValidationLevel = "EXISTS" | "SIZE" | "SHA256";
export type SizeBytes = number | null;
export type Sha256 = string | null;
export type ArtifactRecords = ArtifactRecord[];
export type CreatedAt = string;
export type UpdatedAt = string;

export interface ProjectState {
  project_id: ProjectId;
  schema_version?: SchemaVersion;
  revision?: Revision;
  lifecycle_state?: LifecycleState;
  run_metadata?: RunMetadata;
  approval_metadata?: ApprovalMetadata;
  structured_errors?: StructuredErrors;
  artifact_records?: ArtifactRecords;
  created_at?: CreatedAt;
  updated_at?: UpdatedAt;
}
export interface RunMetadata {
  [k: string]: unknown;
}
export interface ApprovalMetadata {
  [k: string]: unknown;
}
export interface ArtifactRecord {
  path: Path;
  validation: ValidationLevel;
  size_bytes?: SizeBytes;
  sha256?: Sha256;
  [k: string]: unknown;
}
