# -*- coding: utf-8 -*-
"""build_ground_truth.py — يولّد فهارس ground-truth من مسح فعلي للقرص.
Zero-hardcode: كل سطر خرج من scan حقيقي. Exit 1 عند أي فشل."""
import json, re, sys, hashlib
from pathlib import Path
from datetime import datetime

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

SCRIPT = Path(__file__).resolve()
DST = SCRIPT.parent.parent            # super-video-maker
WS  = DST.parent.parent.parent        # video-workspace
OUT = DST / "ground-truth"
OUT.mkdir(parents=True, exist_ok=True)
TS  = datetime.now().isoformat(timespec="seconds")

def hdr(title, src, extra=""):
    return (f"# {title}\n> AUTO-GENERATED by build_ground_truth.py — DO NOT EDIT BY HAND\n"
            f"> Source: `{src}` | Generated: {TS}{extra}\n\n")

def fam_of(n):
    n = n.lower()
    if n.startswith("logo-") or n in ("lower-third", "subscribe-reminder"): return "Branding & Logos"
    if any(k in n for k in ("chart", "stat", "progress", "counter", "comparison")): return "Data & Stats"
    if any(k in n for k in ("transition", "wipe", "dissolve", "whip", "morph", "iris", "blinds", "pixel", "fade", "zoom-through", "clock")): return "Transitions"
    if any(k in n for k in ("noise", "film", "bokeh", "gradient", "grid", "geometric", "liquid", "matrix", "starfield", "sound-wave", "particle", "camera-shake", "vignette")): return "VFX & Overlays"
    if any(k in n for k in ("picture", "card", "carousel", "gallery", "photo", "polaroid", "stack", "notification", "parallax", "zoom-reveal", "split", "masonry")): return "Containers & Cards"
    if any(k in n for k in ("countdown", "end-card", "ken-burns", "letterbox", "spotlight", "credits")): return "CTA & Engagement"
    if any(k in n for k in ("text", "title", "quote", "typewriter", "glitch", "bubble", "popping", "bounce", "pulsing", "highlight", "list", "chapter")): return "Typography & Captions"
    return "Unclassified"

# ── 1) TEMPLATE_CATALOG & TEMPLATE_INDEX ─────────────────────────────
templates_dir = DST / "templates"
engine_dir = DST / "engine"
(OUT / "collections").mkdir(parents=True, exist_ok=True)

catalog = []
PREMIUM_PATHS = [
    "elements/typography/blur-reveal", "elements/typography/rgb-glitch-text",
    "elements/typography/tracking-in", "elements/typography/typewriter",
    "elements/typography/word-stagger", "elements/typography/text-reveal",
    "elements/captions/captions", "elements/code/code-block",
    "elements/code/code-diff", "elements/code/terminal",
    "elements/ui/split-screen", "elements/ui/remocn-ui",
    "elements/ui/remotion-bits", "elements/data/AudioVisualizer",
    "elements/data/StatCard", "scenes/social/social-clip",
    "scenes/social/SocialClip", "scenes/product/ken-burns",
    "effects/transitions/glass-wipe", "effects/transitions/type-mask",
    "effects/transitions/blur-out-up", "effects/transitions/whip-pan",
    "elements/typography/caret", "elements/typography/typewriter-remocn"
]

def get_quality(relative_path, source_name):
    if source_name == "engine":
        return "A"
    for p in PREMIUM_PATHS:
        if p in relative_path:
            return "A"
    return "C"

def get_rtl_ready(relative_path):
    rtl_dirs = ["elements/typography", "elements/captions"]
    for d in rtl_dirs:
        if d in relative_path:
            return True
    return False

REMOCN_PATHS = [
    "elements/typography/caret",
    "elements/typography/typewriter-remocn",
    "effects/transitions/blur-out-up",
    "effects/transitions/whip-pan",
    "elements/ui/remocn-ui"
]

def get_source(relative_path, source_name):
    if source_name == "engine":
        return "cinematic-engine"
        
    for p in REMOCN_PATHS:
        if p in relative_path:
            return "remocn"
    
    PREMIUM_PATHS_SOURCE = [
        "elements/typography/blur-reveal", "elements/typography/rgb-glitch-text",
        "elements/typography/tracking-in", "elements/typography/typewriter",
        "elements/typography/word-stagger", "elements/typography/text-reveal",
        "elements/captions/captions", "elements/code/code-block",
        "elements/code/code-diff", "elements/code/terminal",
        "elements/ui/split-screen", "elements/ui/remocn-ui",
        "elements/ui/remotion-bits", "elements/data/AudioVisualizer",
        "elements/data/StatCard", "scenes/social/social-clip",
        "scenes/social/SocialClip", "scenes/product/ken-burns",
        "effects/transitions/glass-wipe", "effects/transitions/type-mask",
        "effects/transitions/blur-out-up", "effects/transitions/whip-pan",
        "elements/typography/caret", "elements/typography/typewriter-remocn"
    ]
    
    for p in PREMIUM_PATHS_SOURCE:
        if p in relative_path:
            if "remocn" in relative_path:
                return "remocn"
            if "remotion-bits" in relative_path:
                return "remotion-bits"
            return "premium"
    
    return "legacy"


def scan_templates(base_dir, source_name):
    if not base_dir.exists(): return
    for f in sorted(list(base_dir.rglob("*.tsx")) + list(base_dir.rglob("*.ts"))):
        if f.name == "index.ts" or f.name.endswith(".d.ts") or f.name == "schema.ts": continue
        rel_path = f.relative_to(base_dir.parent).as_posix()
        parts = rel_path.split("/")
        
        t_type = "misc"
        t_family = "core"
        if len(parts) >= 3:
            t_type = parts[1]
            if t_type == "scenes": t_type = "scene"
            elif t_type == "elements": t_type = "element"
            elif t_type == "effects": t_type = "effect"
            elif source_name == "engine": 
                if t_type == "scenes": t_type = "scene"
                else: t_type = "engine"
            
            t_family = parts[2] if len(parts) > 3 else "core"
            if source_name == "engine" and t_type == "engine":
                t_family = parts[1]
        
        id_path = "/".join(parts[1:-1]) if len(parts) > 2 else f.stem
        catalog.append({
            "id": f"{id_path}/{f.stem}" if not id_path.endswith(f.stem) else id_path,
            "name": f.stem.replace("-", " ").title().replace(" ", ""),
            "type": t_type,
            "family": t_family,
            "quality": get_quality(rel_path, source_name),
            "status": "production-ready",
            "rtl_ready": get_rtl_ready(rel_path),
            "source": get_source(rel_path, source_name),
            "path": rel_path,
            "use_cases": [],
            "intents": [],
            "moods": [],
            "capabilities": [],
            "notes": ""
        })

scan_templates(templates_dir, "new_unified")
scan_templates(engine_dir, "engine")

# --- Classify Templates ---
import sys
sys.path.append(str(DST / "scripts"))
try:
    import classify_templates
    for item in catalog:
        f = item.get("family", "")
        n = item.get("name", "")
        p = item.get("path", "")
        t = item.get("type", "")
        q = item.get("quality", "C")
        s = item.get("source", "")
        
        item["use_cases"] = classify_templates.get_use_cases(f, n, p)
        item["intents"] = classify_templates.get_intents(f, n, t)
        item["moods"] = classify_templates.get_moods(f, n, q)
        item["capabilities"] = classify_templates.get_capabilities(f, n, s)
except ImportError:
    print("Warning: classify_templates not found, skipping classification.")





catalog_path = OUT / "template_catalog.json"
import json
catalog_path.write_text(json.dumps(catalog, indent=2, ensure_ascii=False), encoding="utf-8")

collections = {
    "ads": {"use_cases": ["ad"]},
    "explainers": {"use_cases": ["explainer", "education"]},
    "social": {"use_cases": ["social"]},
    "saas": {"use_cases": ["saas", "product"]},
    "product": {"use_cases": ["product", "launch"]}
}
for col_name, col_data in collections.items():
    uc = col_data['use_cases'][0]
    
    lines = [f"# {col_name.title()} Collection",
             "> مولّد آلياً من template_catalog.json",
             f"> آخر تحديث: {TS[:10]}", ""]
             
    for cat_name, type_filter in [("مشاهد (Scenes)", "scene"), ("عناصر (Elements)", "element"), ("تأثيرات (Effects)", "effect")]:
        lines.extend([f"## {cat_name}", "| Name | Quality | Path | Intents |", "|---|---|---|---|"])
        
        found = False
        for item in catalog:
            if uc in item.get("use_cases", []) and item.get("type") == type_filter:
                intents_str = ", ".join(item.get("intents", []))
                lines.append(f"| `{item['name']}` | {item['quality']} | `{item['path']}` | {intents_str} |")
                found = True
        if not found:
            lines.append("| (لا يوجد) | - | - | - |")
        lines.append("")
        
    (OUT / "collections" / f"{col_name}.md").write_text("\n".join(lines), encoding="utf-8")

lines = []
lines.append("| File | Type | Family | Source | Path |")
lines.append("|---|---|---|---|---|")
for c in catalog:
    lines.append(f"| `{c['name']}` | {c['type']} | {c['family']} | {c['source']} | `{c['path']}` |")

count = len(catalog)
import hashlib
(OUT / "TEMPLATE_INDEX.md").write_text(
    hdr("TEMPLATE_INDEX — القوالب الحقيقية على القرص", "template_catalog.json", f" | SHA256: {hashlib.sha256(json.dumps(catalog).encode()).hexdigest()[:16]}")
    + f"**العدد: {count} قالباً**\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
print(f"TEMPLATE_INDEX: {count}")

# ── 2) MCP_INDEX ──────────────────────────────────
out, servers = ["| Server | Tool | Signature |", "|---|---|---|"], 0
for srv in sorted((DST / "tools" / "mcp-servers").iterdir()):
    if not srv.is_dir(): continue
    found = []
    for py in sorted(srv.rglob("*.py")):
        if any(p.startswith(".venv") or p == "site-packages" or p == "__pycache__" for p in py.parts):
            continue
        src = py.read_text(encoding="utf-8")
        for m in re.finditer(r"@\w+\.tool\(\)\s*\n\s*(?:async\s+)?def\s+(\w+)\s*\(([^)]*)\)", src):
            found.append((m.group(1), re.sub(r"\s+", " ", m.group(2).strip())))
    for js in sorted(srv.glob("*.js")) + sorted(srv.glob("*.ts")):
        if any(p == "node_modules" for p in js.parts):
            continue
        src = js.read_text(encoding="utf-8")
        for m in re.finditer(r"name:\s*['\"]([a-zA-Z0-9_-]+)['\"](?:.*?properties:\s*\{(.*?)\})?", src, re.S):
            tool_name = m.group(1)
            if tool_name == srv.name:
                continue
            props = ""
            if m.group(2):
                prop_names = re.findall(r"(\w+):\s*\{", m.group(2))
                props = ", ".join(prop_names)
            found.append((tool_name, props))
    if found:
        servers += 1
        out += [f"| `{srv.name}` | `{n}` | `({a})` |" for n, a in found]


(OUT / "MCP_INDEX.md").write_text(hdr("MCP_INDEX — أدوات MCP الحقيقية", "tools/mcp-servers/*")
    + f"**الخوادم: {servers}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"MCP_INDEX: {servers}")

# ── 3) TOOLS_INDEX ────────────────────────────────
out, n = ["| Tool | الوصف (أول سطر docstring) |", "|---|---|"], 0
tool_files = sorted(list((DST / "tools").glob("*.py")) + [p for p in (DST / "scripts").glob("*.py") if p.name == "materialize_project.py"])
for py in tool_files:
    m = re.search(r'"""(.*?)"""', py.read_text(encoding="utf-8"), re.S)
    desc = m.group(1).strip().splitlines()[0] if m and m.group(1).strip() else "—"
    n += 1; out.append(f"| `{py.name}` | {desc} |")
(OUT / "TOOLS_INDEX.md").write_text(hdr("TOOLS_INDEX — أدوات Python", "tools/*.py + scripts/materialize_project.py")
    + f"**العدد: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"TOOLS_INDEX: {n}")

# ── 4) RECIPES_INDEX ──────────────────────────────
out, n = ["| Recipe | الاسم / الهدف |", "|---|---|"], 0
for j in sorted((DST / "recipes").glob("*.json")):
    if j.name == "schema.json": continue
    try: data = json.loads(j.read_text(encoding="utf-8"))
    except Exception: data = {}
    name = data.get("name") or data.get("id") or j.stem
    desc = str(data.get("description") or data.get("goal") or "")[:140]
    n += 1; out.append(f"| `{j.stem}` | {name} — {desc} |")
(OUT / "RECIPES_INDEX.md").write_text(hdr("RECIPES_INDEX — الوصفات", "recipes/*.json")
    + f"**العدد: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"RECIPES_INDEX: {n}")

# ── 5) PLAYBOOKS_INDEX ────────────────────────────
SKIP = {"README.md", "SKILL.md", "REFERENCE.md", "ROUTER.md", "AUDIT_REPORT.md"}
out, n = ["| Playbook | العنوان |", "|---|---|"], 0
for md in sorted(DST.glob("*.md")):
    if md.name in SKIP: continue
    first = next((l for l in md.read_text(encoding="utf-8").splitlines() if l.startswith("# ")), "# " + md.stem)
    n += 1; out.append(f"| `{md.name}` | {first[2:].strip()} |")
(OUT / "PLAYBOOKS_INDEX.md").write_text(hdr("PLAYBOOKS_INDEX — دفاتر التشغيل", "*.md (جذر المهارة)")
    + f"**العدد: {n}**\n\n" + "\n".join(out) + "\n", encoding="utf-8")
print(f"PLAYBOOKS_INDEX: {n}")

# ── 6) CINEMATIC_INDEX ────────────────────────────
def cin_family(rel):
    rel = rel.lower()
    if rel.startswith("engine/audio"): return "Audio & Sync"
    if rel.startswith("engine/camera") or rel.startswith("engine/choreography"): return "Camera & Choreography"
    if rel.startswith("engine/cursor"): return "Cursor"
    if rel.startswith("engine/layout"): return "Layout & Zones"
    if rel.startswith("engine/ui-state"): return "UI State"
    if rel.startswith("primitives/app-ui"): return "App UI Mocks"
    if rel.startswith("primitives"): return "Primitives"
    if rel.startswith("scenes"): return "Scenes"
    return "Core"

lines, n = ["| File | Exports | Props (أول 12) | Family |", "|---|---|---|---|"], 0
ce = DST / "engine"
if ce.exists():
    for f in sorted(list(ce.rglob("*.tsx")) + list(ce.rglob("*.ts"))):
        if f.name == "index.ts": continue
        src = f.read_text(encoding="utf-8")
        exp = re.findall(r"export\s+(?:const|function|class)\s+([A-Za-z_$][\w$]*)", src)
        exp += re.findall(r"export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)", src)
        mdef = re.search(r"export\s+default\s+([A-Za-z_$][\w$]*)", src)
        if mdef: exp.append(mdef.group(1) + " (default)")
        if not exp: continue
        props = []
        mpr = re.search(r"(?:type|interface)\s+\w*Props\w*\s*=\s*\{(.*?)\n\}", src, re.S)
        if mpr: props = re.findall(r"([A-Za-z_$][\w$]*)\s*[?]?:", mpr.group(1))
        n += 1
        rel = f.relative_to(ce).as_posix()
        lines.append(f"| `{rel}` | {', '.join(sorted(set(exp)))} | {', '.join(props[:12]) or '—'} | {cin_family(rel)} |")
(OUT / "CINEMATIC_INDEX.md").write_text(
    hdr("CINEMATIC_INDEX — مكونات المحرك السينمائي على القرص", "cinematic-engine/**/*.tsx|ts")
    + f"**العدد: {n} مكوناً**\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
print(f"CINEMATIC_INDEX: {n}")

print("DONE — جميع الفهارس مولدة من القرص.")
