[project]
name = "image-tools-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp<2.0.0",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
]

[project.scripts]
image-tools-mcp = "image_tools_mcp:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
