"""
tests/ai/contracts/fixtures.py
==============================
Canonical test fixtures (valid and invalid) for all S27.1 AI subsystem contracts.
Used for Python validation, JSON Schema validation, and cross-language parity testing.
"""

from __future__ import annotations

from decimal import Decimal
from datetime import datetime, timezone
from typing import Any, Dict

NOW_ISO = "2026-09-30T17:00:00Z"
LATER_ISO = "2026-09-30T17:00:05Z"
MUCH_LATER_ISO = "2026-09-30T17:00:10Z"


def get_valid_fixtures() -> Dict[str, Dict[str, Any]]:
    """Returns valid dictionary representations for all canonical contracts."""
    return {
        "UsageRecord_minimal": {},
        "UsageRecord_full": {
            "input_tokens": 100,
            "output_tokens": 200,
            "total_tokens": 300,
            "audio_seconds": "15.5",
            "video_seconds": "30.0",
            "image_count": 2,
            "reported_units": [
                {"unit_type": "characters", "quantity": "1500"},
            ],
        },
        "CostEstimate_minimal": {
            "estimated_cost": "0.05",
        },
        "CostEstimate_full": {
            "estimated_cost": "0.1000",
            "reserved_cost": "0.1500",
            "actual_cost": "0.0850",
            "currency": "USD",
            "pricing_version": "v2026.09",
        },
        "AIError_minimal": {
            "code": "PROVIDER_UNAVAILABLE",
            "message": "Primary provider endpoint is currently unreachable",
            "retryable": True,
        },
        "AIError_full": {
            "code": "RATE_LIMITED",
            "message": "Upstream rate limit exceeded for tier 2",
            "retryable": True,
            "details": {"retry_after_seconds": 30, "limit": 100},
            "dependency_reference": "dep_tts_01",
        },
        "ProvenanceRecord_valid": {
            "source": "provider_adapter",
            "model_id": "model_tts_fast",
            "provider_id": "adapter_elevenlabs",
            "timestamp": NOW_ISO,
            "latency_ms": 250,
        },
        "ModelRequirement_minimal": {
            "capability": "TEXT_TO_SPEECH",
        },
        "ModelRequirement_full": {
            "capability": "TEXT_TO_SPEECH",
            "quality_target": "HIGH",
            "budget_constraint": {"estimated_cost": "0.05"},
            "max_latency_ms": 1500,
            "language": "en",
            "privacy_requirement": "ZERO_DATA_RETENTION",
            "media_type": "audio/mp3",
            "required_features": ["streaming", "timestamps"],
        },
        "ModelSelection_valid": {
            "primary_model": "model_tts_neural_v1",
            "fallback_candidates": ["model_tts_standard_v2"],
            "reason_code": "LOWEST_COST_TIER",
            "estimated_cost": {"estimated_cost": "0.02"},
        },
        "CapabilityRequest_valid": {
            "capability_id": "TEXT_TO_SPEECH",
            "capability": "TEXT_TO_SPEECH",
            "input_data": {"text": "Hello world", "voice_id": "voice_123"},
            "requirements": {
                "capability": "TEXT_TO_SPEECH",
                "quality_target": "STANDARD",
            },
            "contract_version": "1.0.0",
        },
        "CapabilityResult_success": {
            "capability_id": "TEXT_TO_SPEECH",
            "capability": "TEXT_TO_SPEECH",
            "status": "SUCCESS",
            "output_data": {"audio_ref": "storage://audio/output.wav"},
            "confidence": 0.95,
            "provenance": {
                "source": "provider_adapter",
                "timestamp": NOW_ISO,
                "latency_ms": 320,
            },
            "usage": {"audio_seconds": "5.2"},
            "error": None,
        },
        "CapabilityResult_failed": {
            "capability_id": "TEXT_TO_SPEECH",
            "capability": "TEXT_TO_SPEECH",
            "status": "FAILED",
            "output_data": None,
            "confidence": None,
            "provenance": {
                "source": "provider_adapter",
                "timestamp": NOW_ISO,
                "latency_ms": 50,
            },
            "usage": {},
            "error": {
                "code": "PROVIDER_UNAVAILABLE",
                "message": "Provider failed",
                "retryable": False,
            },
        },
        "ToolCall_valid": {
            "call_id": "call_12345",
            "tool_name": "crop_video",
            "parameters": {"width": 1080, "height": 1920, "maintain_aspect": True},
            "untrusted_metadata": {"reason": "vertical crop for mobile"},
        },
        "ToolResult_success": {
            "call_id": "call_12345",
            "status": "SUCCESS",
            "output": {"asset_id": "ast_cropped_1"},
            "error": None,
            "started_at": NOW_ISO,
            "completed_at": LATER_ISO,
            "duration_ms": 5000,
        },
        "ToolResult_error": {
            "call_id": "call_12345",
            "status": "ERROR",
            "output": None,
            "error": {
                "code": "DEPENDENCY_FAILED",
                "message": "FFmpeg process returned non-zero code",
                "retryable": False,
            },
            "started_at": NOW_ISO,
            "completed_at": LATER_ISO,
            "duration_ms": 5000,
        },
        "MemoryQuery_valid": {
            "workspace_id": "ws_alpha",
            "project_id": "prj_001",
            "session_id": "sess_100",
            "memory_type": "EPISODIC",
            "query_text": "Find user preferences for font Cairo",
            "limit": 5,
            "minimum_confidence": 0.8,
        },
        "MemoryResult_valid": {
            "entries": [
                {
                    "entry_id": "mem_01",
                    "memory_type": "EPISODIC",
                    "content": "User prefers Cairo font with high contrast subtitle background",
                    "relevance_score": 0.88,
                    "confidence": 0.92,
                    "provenance": {
                        "source": "user_session",
                        "timestamp": NOW_ISO,
                    },
                    "created_at": NOW_ISO,
                }
            ],
            "total_found": 1,
            "query_duration_ms": 42,
        },
        "MediaIntelligenceRef_valid": {
            "artifact_id": "art_analysis_99",
            "asset_id": "ast_video_raw_1",
            "analysis_version": "1.0.0",
            "content_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "storage_key": "ai/media_intelligence/artifacts/art_analysis_99.json",
            "created_at": NOW_ISO,
        },
        "AIRequest_minimal": {
            "request_id": "req_001",
            "workspace_id": "ws_prod",
            "actor_id": "usr_editor_1",
            "capability": "TEXT_TO_SPEECH",
            "created_at": NOW_ISO,
        },
        "AIRequest_full": {
            "request_id": "req_002",
            "workspace_id": "ws_prod",
            "actor_id": "usr_editor_1",
            "project_id": "prj_main",
            "session_id": "sess_chat_9",
            "capability": "VIDEO_GENERATION",
            "intent": "generate_scene_broll",
            "input_data": {"prompt": "Sunset over Arabian dunes", "seconds": 5},
            "quality_target": "HIGH",
            "privacy_requirement": "ZERO_DATA_RETENTION",
            "execution_class": "BATCH",
            "metadata": {"source_scene": 3},
            "created_at": NOW_ISO,
            "contract_version": "1.0.0",
        },
        "AIResponse_success": {
            "request_id": "req_001",
            "run_id": "run_888",
            "status": "SUCCEEDED",
            "result": {"audio_asset": "ast_generated_mp3"},
            "usage": {"audio_seconds": "4.5"},
            "cost": {"estimated_cost": "0.015", "actual_cost": "0.015"},
            "warnings": [],
            "error": None,
            "created_at": LATER_ISO,
            "contract_version": "1.0.0",
        },
        "AIResponse_failed": {
            "request_id": "req_001",
            "run_id": "run_888",
            "status": "FAILED",
            "result": None,
            "usage": {},
            "cost": {"estimated_cost": "0.015"},
            "warnings": ["Quota approaching ceiling"],
            "error": {
                "code": "BUDGET_EXCEEDED",
                "message": "Operation would exceed monthly workspace budget ceiling",
                "retryable": False,
            },
            "created_at": LATER_ISO,
            "contract_version": "1.0.0",
        },
        "AIRun_valid": {
            "run_id": "run_001",
            "workspace_id": "ws_alpha",
            "project_id": "prj_001",
            "session_id": None,
            "status": "RUNNING",
            "capability": "PLANNING",
            "workflow_ref": "recipes/full_video_pipeline.json",
            "created_at": NOW_ISO,
            "started_at": LATER_ISO,
            "completed_at": None,
            "usage": {"input_tokens": 1500, "output_tokens": 500, "total_tokens": 2000},
            "cost": {"estimated_cost": "0.05"},
            "error": None,
            "contract_version": "1.0.0",
        },
        "AIStep_valid": {
            "step_id": "step_001",
            "run_id": "run_001",
            "status": "SUCCEEDED",
            "attempt": 1,
            "capability": "VOICE_ANALYSIS",
            "input_ref": "storage://incoming/voice.mp3",
            "output_ref": "storage://processed/voice_analysis.json",
            "provider": "local_faster_whisper",
            "model": "whisper-large-v3",
            "usage": {"audio_seconds": "32.0"},
            "cost": {"estimated_cost": "0.00", "actual_cost": "0.00"},
            "error": None,
            "created_at": NOW_ISO,
            "started_at": LATER_ISO,
            "completed_at": MUCH_LATER_ISO,
        },
        "PromptContract_valid": {
            "prompt_id": "prompt_translator",
            "version": 1,
            "hash": "7fb88a55e1b7aa8d89114e7f94f04402f9d6ea1585645b4c9dcedac3d8be38bf",
            "status": "DRAFT",
            "template": "Translate to {lang}: {text}",
            "system_prompt": "You are a translator.",
            "variables": ["lang", "text"],
            "created_at": NOW_ISO,
            "workspace_id": "ws_alpha",
            "metadata": {"author": "admin"},
        },
        "PromptRenderRequest_valid": {
            "prompt_id": "prompt_translator",
            "version": 1,
            "variables": {"lang": "ar", "text": "hello"},
            "workspace_id": "ws_alpha",
        },
        "PromptRenderResult_valid": {
            "prompt_id": "prompt_translator",
            "version": 1,
            "hash": "7fb88a55e1b7aa8d89114e7f94f04402f9d6ea1585645b4c9dcedac3d8be38bf",
            "rendered_text": "Translate to ar: hello",
            "system_prompt": "You are a translator.",
            "status": "PRODUCTION",
        },
        "TraceSpanRecord_valid": {
            "trace_id": "trc_12345",
            "span_id": "spn_67890",
            "parent_span_id": None,
            "span_type": "MODEL_ROUTE",
            "name": "Route Model",
            "run_id": "run_001",
            "step_id": "step_001",
            "activity_id": "act_001",
            "workspace_id": "ws_alpha",
            "project_id": "prj_001",
            "capability": "TEXT_GENERATION",
            "provider": "adapter_openai",
            "model": "gpt-4o",
            "prompt_id": "prompt_translator",
            "prompt_version": "1",
            "started_at": NOW_ISO,
            "ended_at": LATER_ISO,
            "duration_ms": 150.0,
            "input_tokens": 100,
            "output_tokens": 50,
            "cache_hit": False,
            "retry_count": 0,
            "fallback": False,
            "estimated_cost": "0.005",
            "actual_cost": "0.005",
            "quality_score": 0.95,
            "status": "SUCCESS",
            "error_code": None,
            "attributes": {"model_tier": "FAST"},
        },
        "AITrace_valid": {
            "trace_id": "trc_12345",
            "run_id": "run_001",
            "workspace_id": "ws_alpha",
            "spans": [],
        },
        "EvalDatasetContract_valid": {
            "dataset_id": "dataset_test_routing",
            "version": "1.0.0",
            "content_hash": "ddbcd176958ee3e228430f80b6a7a352a1bb60550343c99648155d268e00dfc5",
            "capability": "TEXT_GENERATION",
            "description": "Test dataset",
            "examples": [
                {
                    "example_id": "ex1",
                    "input_payload": {"query": "test"},
                    "expected_output": None,
                    "expected_schema": None,
                    "ground_truth_label": "ans1",
                    "is_human_verified": False,
                    "min_quality_score": 0.8,
                }
            ],
        },
        "EvalResultContract_valid": {
            "evaluation_id": "eval_001",
            "dataset_id": "dataset_test_routing",
            "dataset_version": "1.0.0",
            "candidate_type": "MODEL",
            "candidate_id": "model_tts_fast",
            "candidate_version": "v1",
            "passed": True,
            "quality_score": 0.92,
            "cost_score": 0.005,
            "latency_ms": 320.0,
            "evaluators_used": ["DETERMINISTIC", "SCHEMA_BASED"],
            "created_at": NOW_ISO,
            "failure_reasons": [],
            "metrics": {},
        },
        "BenchmarkDebtContract_valid": {
            "benchmark_id": "BENCH_SPEECH_QUALITY",
            "name": "Speech Real Quality Benchmark",
            "status": "DEFERRED_FINAL_VALIDATION",
            "target_stage": "AI-15",
            "fake_scores_injected": False,
            "notes": "Awaiting real audio stems",
        },
    }
