"""
tests/core/test_s17_render_input.py — Comprehensive Unit & Integration Tests for Package S17:
- Test A: Semantic parity across consumers (Local, Docker, Studio, Probe).
- Test B: Deterministic envelope generation.
- Test C: Missing 05_blueprint.json fails closed.
- Test D: Missing media_map.json fails closed.
- Test E: Unresolved media references fail closed.
- Test F: Project ID mismatch fails closed.
- Test G: Corrupt JSON in project/brand/overrides fails closed.
- Test H: overrides.json list format normalized to dict.
- Test I: 02_asset_manifest.json included in envelope when present.
- Test J: render_props.json written to disk properly.
- Test K: Cross-language roundtrip: payload generated by build_render_input passes parseRenderInput() in TS.
"""
import json
import subprocess
from pathlib import Path
import pytest

from scripts.core.render_input import (
    build_render_input,
    get_render_props_path,
    RenderInputError,
    RenderInputMissingArtifactError,
    RenderInputValidationError,
    RenderInputProjectMismatchError,
    DEFAULT_BRAND_KIT,
)

ROOT = Path(__file__).resolve().parent.parent.parent


def create_minimal_valid_project(proj_dir: Path, project_id: str):
    """Scaffolds a valid minimal project directory for testing."""
    proj_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. 05_blueprint.json
    bp = {
        "blueprint_version": "2.0.0",
        "project_id": project_id,
        "fps": 30,
        "aspect_ratio": "16:9",
        "scenes": [
            {
                "scene_id": "scene_01",
                "template": "HeroDeviceAssembleWrapper",
                "startFrame": 0,
                "durationFrames": 60,
                "surface": {},
                "media_refs": ["ast_img_1"],
                "content": {
                    "text": "Hello World"
                }
            }
        ]
    }
    (proj_dir / "05_blueprint.json").write_text(json.dumps(bp, indent=2), encoding="utf-8")

    # 2. media_map.json
    media_map = {
        "ast_img_1": f"projects/{project_id}/test.png"
    }
    (proj_dir / "media_map.json").write_text(json.dumps(media_map, indent=2), encoding="utf-8")

    # 3. brand.json
    brand = {
        "brandName": "Test Brand",
        "colors": {
            "primary": "#FF0000",
            "accent": "#00FF00",
            "background": "#000000",
            "text": "#FFFFFF"
        },
        "fonts": {
            "display": "Cairo",
            "body": "Cairo"
        }
    }
    (proj_dir / "brand.json").write_text(json.dumps(brand, indent=2), encoding="utf-8")

    # 4. project.json
    project_meta = {
        "title": "Test Title",
        "fps": 30,
        "project_id": project_id
    }
    (proj_dir / "project.json").write_text(json.dumps(project_meta, indent=2), encoding="utf-8")

    # 5. overrides.json
    overrides = {
        "scenes": {
            "scene_01": {
                "props": {"text": "Overridden Text"}
            }
        }
    }
    (proj_dir / "overrides.json").write_text(json.dumps(overrides, indent=2), encoding="utf-8")


def test_s17_case_a_semantic_parity_across_consumers(tmp_path):
    """Case A: Single authority produces identical payload for all execution environments."""
    proj_dir = tmp_path / "prj_parity_01"
    create_minimal_valid_project(proj_dir, "prj_parity_01")

    envelope1 = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False, write_to_disk=False)
    envelope2 = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False, write_to_disk=True)

    props_file = get_render_props_path(proj_dir, workspace_root=ROOT)
    assert props_file.is_file()
    disk_envelope = json.loads(props_file.read_text(encoding="utf-8"))

    assert envelope1 == envelope2 == disk_envelope
    assert "projectData" in envelope1
    pdata = envelope1["projectData"]
    assert pdata["project"]["project_id"] == "prj_parity_01"
    assert pdata["blueprint"]["project_id"] == "prj_parity_01"
    assert pdata["brand"]["brandName"] == "Test Brand"
    assert "ast_img_1" in pdata["media_map"]


def test_s17_case_b_deterministic_output(tmp_path):
    """Case B: Output is byte-for-byte deterministic across multiple runs."""
    proj_dir = tmp_path / "prj_det_02"
    create_minimal_valid_project(proj_dir, "prj_det_02")

    build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False, write_to_disk=True)
    props_path = get_render_props_path(proj_dir)
    bytes1 = props_path.read_bytes()

    build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False, write_to_disk=True)
    bytes2 = props_path.read_bytes()

    assert bytes1 == bytes2


def test_s17_case_c_missing_blueprint_fails_closed(tmp_path):
    """Case C: Missing 05_blueprint.json raises RenderInputMissingArtifactError."""
    proj_dir = tmp_path / "prj_no_bp_03"
    create_minimal_valid_project(proj_dir, "prj_no_bp_03")
    (proj_dir / "05_blueprint.json").unlink()

    with pytest.raises(RenderInputMissingArtifactError) as exc_info:
        build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)

    assert "05_blueprint.json" in str(exc_info.value)


def test_s17_case_d_missing_media_map_fails_closed(tmp_path):
    """Case D: Missing media_map.json raises RenderInputValidationError."""
    proj_dir = tmp_path / "prj_no_media_04"
    create_minimal_valid_project(proj_dir, "prj_no_media_04")
    (proj_dir / "media_map.json").unlink()

    with pytest.raises(RenderInputValidationError) as exc_info:
        build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)

    assert "media_map.json" in str(exc_info.value)


def test_s17_case_e_unresolved_media_reference_fails_closed(tmp_path):
    """Case E: Media reference in blueprint not in media_map fails closed."""
    proj_dir = tmp_path / "prj_unresolved_05"
    create_minimal_valid_project(proj_dir, "prj_unresolved_05")
    # media_map has ast_img_1, but blueprint has ast_img_999
    bp = json.loads((proj_dir / "05_blueprint.json").read_text(encoding="utf-8"))
    bp["scenes"][0]["media_refs"] = ["ast_img_999"]
    (proj_dir / "05_blueprint.json").write_text(json.dumps(bp), encoding="utf-8")

    with pytest.raises(RenderInputValidationError) as exc_info:
        build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)

    assert "Unresolved media references" in str(exc_info.value)


def test_s17_case_f_project_id_mismatch_fails_closed(tmp_path):
    """Case F: project.json project_id mismatch fails closed."""
    proj_dir = tmp_path / "prj_mismatch_06"
    create_minimal_valid_project(proj_dir, "prj_mismatch_06")
    proj_meta = json.loads((proj_dir / "project.json").read_text(encoding="utf-8"))
    proj_meta["project_id"] = "prj_attacker_override"
    (proj_dir / "project.json").write_text(json.dumps(proj_meta), encoding="utf-8")

    with pytest.raises(RenderInputProjectMismatchError) as exc_info:
        build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)

    assert "prj_attacker_override" in str(exc_info.value)


def test_s17_case_g_corrupt_json_fails_closed(tmp_path):
    """Case G: Corrupt JSON in brand.json or project.json fails closed."""
    proj_dir = tmp_path / "prj_corrupt_07"
    create_minimal_valid_project(proj_dir, "prj_corrupt_07")
    (proj_dir / "brand.json").write_text("{ corrupt json ...", encoding="utf-8")

    with pytest.raises(RenderInputValidationError) as exc_info:
        build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)

    assert "brand.json" in str(exc_info.value)


def test_s17_case_h_overrides_list_format_normalized(tmp_path):
    """Case H: overrides.json with list of scenes is normalized to dict."""
    proj_dir = tmp_path / "prj_norm_08"
    create_minimal_valid_project(proj_dir, "prj_norm_08")
    # write list format as produced by scaffold
    (proj_dir / "overrides.json").write_text(json.dumps({
        "project_id": "prj_norm_08",
        "scenes": [
            {"scene_id": "scene_01", "props": {"title": "Updated"}}
        ]
    }), encoding="utf-8")

    envelope = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)
    overrides = envelope["projectData"]["overrides"]
    assert isinstance(overrides["scenes"], dict)
    assert "scene_01" in overrides["scenes"]
    assert overrides["scenes"]["scene_01"]["props"]["title"] == "Updated"


def test_s17_case_i_manifest_included_when_present(tmp_path):
    """Case I: 02_asset_manifest.json is loaded and included in envelope when present."""
    proj_dir = tmp_path / "prj_manifest_09"
    create_minimal_valid_project(proj_dir, "prj_manifest_09")
    manifest = {
        "manifest_version": "2.0.0",
        "project_id": "prj_manifest_09",
        "created_at": "2026-09-28T12:00:00Z",
        "assets": [
            {
                "asset_id": "ast_img_1",
                "kind": "image",
                "provenance": "user_upload",
                "status": "ready",
                "processed_path": "projects/prj_manifest_09/test.png",
                "metadata": {}
            }
        ]
    }
    (proj_dir / "02_asset_manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    envelope = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)
    assert "asset_manifest" in envelope["projectData"]
    assert envelope["projectData"]["asset_manifest"]["manifest_version"] == "2.0.0"


def test_s17_case_j_brand_defaults_applied_when_missing(tmp_path):
    """Case J: When brand.json is omitted, DEFAULT_BRAND_KIT is provided."""
    proj_dir = tmp_path / "prj_nobrand_10"
    create_minimal_valid_project(proj_dir, "prj_nobrand_10")
    (proj_dir / "brand.json").unlink()

    envelope = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False)
    brand = envelope["projectData"]["brand"]
    assert brand["brandName"] == DEFAULT_BRAND_KIT["brandName"]
    assert brand["colors"]["primary"] == DEFAULT_BRAND_KIT["colors"]["primary"]


def test_s17_case_k_cross_language_parse_render_input_roundtrip(tmp_path):
    """
    Case K: The envelope generated by build_render_input must pass
    parseRenderInput() in TypeScript without errors.
    """
    import os
    proj_dir = tmp_path / "prj_ts_roundtrip_11"
    create_minimal_valid_project(proj_dir, "prj_ts_roundtrip_11")

    envelope = build_render_input(proj_dir, workspace_root=ROOT, verify_files_on_disk=False, write_to_disk=True)
    props_file = get_render_props_path(proj_dir)

    env = os.environ.copy()
    env["LIVE_RENDER_PROPS_PATH"] = str(props_file.resolve())

    res = subprocess.run(
        ["npx", "vitest", "run", "tests/remotion/s17_render_input_parity.test.ts"],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=env,
    )
    assert res.returncode == 0, f"TypeScript parseRenderInput failed:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}"
    assert "passed" in res.stdout
