"""
ai/models/definitions.py
========================
Canonical reference model definitions for S27.

Demonstrates provider-neutral models, versioned Decimal pricing,
and explicit capability bindings across the platform.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import List

from ai.contracts.common import CapabilityType, QualityTarget
from ai.capabilities.types import CapabilityPrivacyClass
from ai.models.types import (
    CostTier,
    LatencyTier,
    ModelDefinition,
    ModelPricing,
)

BASE_PRICING_DATE = datetime(2026, 9, 30, 0, 0, 0, tzinfo=timezone.utc)

CANONICAL_MODELS_LIST: List[ModelDefinition] = [
    # 1. OpenAI GPT-4o
    ModelDefinition(
        model_id="gpt-4o",
        provider_id="openai",
        display_name="GPT-4o Omnimodal",
        capabilities=[
            CapabilityType.TEXT_GENERATION,
            CapabilityType.REASONING,
            CapabilityType.PLANNING,
            CapabilityType.SUMMARIZATION,
            CapabilityType.TRANSLATION,
            CapabilityType.VISION,
            CapabilityType.OCR,
            CapabilityType.CAPTIONING,
        ],
        quality_profile=QualityTarget.HIGH,
        cost_profile=CostTier.MEDIUM,
        latency_profile=LatencyTier.FAST,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=True,
        supports_tools=True,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=True,
        context_limit=128000,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            input_token_price=Decimal("0.000005"),
            output_token_price=Decimal("0.000015"),
        ),
    ),

    # 2. Google Gemini 1.5 Pro
    ModelDefinition(
        model_id="gemini-1.5-pro",
        provider_id="gemini",
        display_name="Gemini 1.5 Pro",
        capabilities=[
            CapabilityType.TEXT_GENERATION,
            CapabilityType.REASONING,
            CapabilityType.PLANNING,
            CapabilityType.SUMMARIZATION,
            CapabilityType.TRANSLATION,
            CapabilityType.VISION,
            CapabilityType.VIDEO_UNDERSTANDING,
            CapabilityType.OCR,
            CapabilityType.CAPTIONING,
        ],
        quality_profile=QualityTarget.HIGH,
        cost_profile=CostTier.MEDIUM,
        latency_profile=LatencyTier.FAST,
        reliability=0.998,
        languages=["*"],
        supports_structured_output=True,
        supports_tools=True,
        supports_audio=True,
        supports_video=True,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=True,
        context_limit=2000000,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            input_token_price=Decimal("0.0000035"),
            output_token_price=Decimal("0.0000105"),
        ),
    ),

    # 3. Anthropic Claude 3.5 Sonnet
    ModelDefinition(
        model_id="claude-3-5-sonnet",
        provider_id="anthropic",
        display_name="Claude 3.5 Sonnet",
        capabilities=[
            CapabilityType.TEXT_GENERATION,
            CapabilityType.REASONING,
            CapabilityType.PLANNING,
            CapabilityType.SUMMARIZATION,
            CapabilityType.TRANSLATION,
            CapabilityType.VISION,
            CapabilityType.OCR,
        ],
        quality_profile=QualityTarget.ULTRA,
        cost_profile=CostTier.HIGH,
        latency_profile=LatencyTier.FAST,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=True,
        supports_tools=True,
        supports_audio=False,
        supports_video=False,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=True,
        context_limit=200000,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            input_token_price=Decimal("0.000003"),
            output_token_price=Decimal("0.000015"),
        ),
    ),

    # 4. ElevenLabs Multilingual v2
    ModelDefinition(
        model_id="eleven-multilingual-v2",
        provider_id="elevenlabs",
        display_name="ElevenLabs Multilingual v2",
        capabilities=[
            CapabilityType.TEXT_TO_SPEECH,
            CapabilityType.VOICE_ANALYSIS,
        ],
        quality_profile=QualityTarget.ULTRA,
        cost_profile=CostTier.MEDIUM,
        latency_profile=LatencyTier.FAST,
        reliability=0.995,
        languages=["en", "ar", "es", "fr", "de", "ja"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=False,
        supports_streaming=True,
        privacy_class=CapabilityPrivacyClass.SENSITIVE_ALLOWED,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            character_price=Decimal("0.000030"),
        ),
    ),

    # 5. Fal.ai Flux Pro
    ModelDefinition(
        model_id="flux-pro",
        provider_id="fal",
        display_name="Flux Pro Diffusion",
        capabilities=[
            CapabilityType.IMAGE_GENERATION,
        ],
        quality_profile=QualityTarget.ULTRA,
        cost_profile=CostTier.HIGH,
        latency_profile=LatencyTier.MODERATE,
        reliability=0.990,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=False,
        supports_video=False,
        supports_batch=True,
        supports_cache=False,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            image_price=Decimal("0.0500"),
        ),
    ),

    # 6. Replicate Zeroscope Video
    ModelDefinition(
        model_id="zeroscope-v2-xl",
        provider_id="replicate",
        display_name="Zeroscope v2 XL Video Generation",
        capabilities=[
            CapabilityType.VIDEO_GENERATION,
        ],
        quality_profile=QualityTarget.STANDARD,
        cost_profile=CostTier.HIGH,
        latency_profile=LatencyTier.SLOW,
        reliability=0.980,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=False,
        supports_video=True,
        supports_batch=False,
        supports_cache=False,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            video_minute_price=Decimal("0.8000"),
        ),
    ),

    # 7. Local Whisper Large v3
    ModelDefinition(
        model_id="whisper-large-v3",
        provider_id="local",
        display_name="Local Whisper Large v3",
        capabilities=[
            CapabilityType.SPEECH_TO_TEXT,
            CapabilityType.LANGUAGE_DETECTION,
            CapabilityType.SPEECH_ALIGNMENT,
        ],
        quality_profile=QualityTarget.HIGH,
        cost_profile=CostTier.FREE,
        latency_profile=LatencyTier.FAST,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=False,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.LOCAL_ONLY,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            audio_minute_price=Decimal("0.0000"),
        ),
    ),

    # 7b. Local Faster-Whisper Base (S28-M04 Default Parity Candidate)
    ModelDefinition(
        model_id="faster-whisper-base",
        provider_id="local",
        display_name="Local Faster-Whisper Base",
        capabilities=[
            CapabilityType.SPEECH_TO_TEXT,
            CapabilityType.LANGUAGE_DETECTION,
            CapabilityType.SPEECH_ALIGNMENT,
        ],
        quality_profile=QualityTarget.STANDARD,
        cost_profile=CostTier.FREE,
        latency_profile=LatencyTier.FAST,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.LOCAL_ONLY,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            audio_minute_price=Decimal("0.0000"),
        ),
    ),

    # 7c. Local Faster-Whisper Tiny (S28-M04 Draft / Low-Latency Tier)
    ModelDefinition(
        model_id="faster-whisper-tiny",
        provider_id="local",
        display_name="Local Faster-Whisper Tiny",
        capabilities=[
            CapabilityType.SPEECH_TO_TEXT,
            CapabilityType.LANGUAGE_DETECTION,
            CapabilityType.SPEECH_ALIGNMENT,
        ],
        quality_profile=QualityTarget.DRAFT,
        cost_profile=CostTier.FREE,
        latency_profile=LatencyTier.REALTIME,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.LOCAL_ONLY,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            audio_minute_price=Decimal("0.0000"),
        ),
    ),

    # 8. Local Demucs
    ModelDefinition(
        model_id="demucs-v4",
        provider_id="local",
        display_name="Demucs v4 Stem Separation",
        capabilities=[
            CapabilityType.VOCAL_ISOLATION,
            CapabilityType.AUDIO_DENOISE,
        ],
        quality_profile=QualityTarget.HIGH,
        cost_profile=CostTier.FREE,
        latency_profile=LatencyTier.MODERATE,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=False,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=False,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.LOCAL_ONLY,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            audio_minute_price=Decimal("0.0000"),
        ),
    ),

    # 9. MCP FFmpeg Audio Engine
    ModelDefinition(
        model_id="mcp-ffmpeg-audio",
        provider_id="mcp",
        display_name="MCP FFmpeg Audio Analyzer",
        capabilities=[
            CapabilityType.BEAT_DETECTION,
            CapabilityType.AUDIO_ENHANCE,
        ],
        quality_profile=QualityTarget.STANDARD,
        cost_profile=CostTier.FREE,
        latency_profile=LatencyTier.FAST,
        reliability=0.999,
        languages=["*"],
        supports_structured_output=False,
        supports_tools=True,
        supports_audio=True,
        supports_video=False,
        supports_batch=True,
        supports_cache=False,
        supports_streaming=False,
        privacy_class=CapabilityPrivacyClass.LOCAL_ONLY,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.09.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            request_price=Decimal("0.0000"),
        ),
    ),

    # 10. OpenRouter Development Gateway Model (S28)
    ModelDefinition(
        model_id="openrouter-dev-model",
        provider_id="openrouter",
        display_name="OpenRouter Development Gateway Model",
        capabilities=[
            CapabilityType.REASONING,
            CapabilityType.PLANNING,
            CapabilityType.VISION,
        ],
        quality_profile=QualityTarget.HIGH,
        cost_profile=CostTier.LOW,
        latency_profile=LatencyTier.FAST,
        reliability=0.995,
        languages=["*"],
        supports_structured_output=True,
        supports_tools=True,
        supports_audio=False,
        supports_video=False,
        supports_batch=True,
        supports_cache=True,
        supports_streaming=True,
        context_limit=1000000,
        privacy_class=CapabilityPrivacyClass.PUBLIC_SAFE,
        enabled=True,
        pricing=ModelPricing(
            pricing_version="2026.10.dev.v1",
            valid_from=BASE_PRICING_DATE,
            currency="USD",
            input_token_price=Decimal("0.0000001"),
            output_token_price=Decimal("0.0000004"),
        ),
    ),
]
