"""
tests/ai/prompts/test_prompt_cache.py
======================================
Integration tests verifying Prompt Version impact on AI Cache (S27.18 + S27.12).

Invariants verified:
1. Cache key incorporates prompt_version:
   - Request with prompt v1 -> cache MISS -> provider executed -> cached.
   - Second request with prompt v1 -> cache HIT -> provider not executed.
   - Same request with prompt v2 -> cache MISS -> provider executed -> new cached entry.
2. Artifact produced under prompt v1 is NEVER returned for prompt v2.
"""

from datetime import datetime, timezone
import json
import pytest

from ai.cache.service import AICacheService
from ai.contracts.cache import AICacheKeyParams
from ai.contracts.capability import CapabilityResult, CapabilityStatus
from ai.contracts.common import CapabilityTypeEnum, ProvenanceRecord
from ai.contracts.usage import UsageRecord
from scripts.core.ai_cache_repository import SQLAICacheRepository
from scripts.core.database import DatabaseEngine
from scripts.core.storage.storage_service import LocalStorageBackend


@pytest.fixture
def cache_service(tmp_path):
    db_file = tmp_path / "test_prompt_cache.db"
    storage_dir = tmp_path / "storage"
    engine = DatabaseEngine(f"sqlite:///{db_file}")
    repo = SQLAICacheRepository(engine=engine)
    storage = LocalStorageBackend(root_dir=storage_dir)
    return AICacheService(repository=repo, storage_service=storage)


def test_prompt_version_cache_invalidation_and_miss(cache_service):
    provider_executions = []

    def fake_provider(prompt_version: str):
        now = datetime.now(timezone.utc)
        output_content = f"Output generated by prompt version {prompt_version}"
        provider_executions.append((prompt_version, output_content))

        result = CapabilityResult(
            capability=CapabilityTypeEnum.TEXT_GENERATION,
            status=CapabilityStatus.SUCCESS,
            output_data={"text": output_content},
            provenance=ProvenanceRecord(
                source="fake_provider",
                model_id="gemini-2.5-flash",
                provider_id="google",
                timestamp=now,
                latency_ms=150,
            ),
            usage=UsageRecord(input_tokens=25, output_tokens=50, total_tokens=75),
        )
        return result, result.model_dump_json().encode("utf-8")

    input_payload = {"topic": "cybersecurity", "tone": "formal"}
    workspace_id = "ws_prompt_cache_test"

    # Step 1: Request with Prompt v1.0.0 -> Cache MISS -> Provider executes
    params_v1 = AICacheKeyParams(
        workspace_id=workspace_id,
        capability=CapabilityTypeEnum.TEXT_GENERATION,
        input_data=input_payload,
        model="gemini-2.5-flash",
        prompt_version="1.0.0",
    )
    res_v1, from_cache_v1 = cache_service.get_or_compute(
        params_v1,
        compute_fn=lambda: fake_provider("1.0.0"),
    )
    assert from_cache_v1 is False
    assert res_v1.output_data["text"] == "Output generated by prompt version 1.0.0"
    assert len(provider_executions) == 1

    # Step 2: Identical request with Prompt v1.0.0 -> Cache HIT -> Provider NOT executed
    res_v1_hit, from_cache_v1_hit = cache_service.get_or_compute(
        params_v1,
        compute_fn=lambda: fake_provider("1.0.0"),
    )
    assert from_cache_v1_hit is True
    assert res_v1_hit.output_data["text"] == "Output generated by prompt version 1.0.0"
    assert len(provider_executions) == 1  # No new execution

    # Step 3: Same input payload, but Prompt updated to v2.0.0 -> Cache MISS -> Provider MUST execute
    params_v2 = AICacheKeyParams(
        workspace_id=workspace_id,
        capability=CapabilityTypeEnum.TEXT_GENERATION,
        input_data=input_payload,
        model="gemini-2.5-flash",
        prompt_version="2.0.0",
    )
    res_v2, from_cache_v2 = cache_service.get_or_compute(
        params_v2,
        compute_fn=lambda: fake_provider("2.0.0"),
    )
    assert from_cache_v2 is False
    assert res_v2.output_data["text"] == "Output generated by prompt version 2.0.0"
    assert len(provider_executions) == 2  # New provider execution recorded

    # Step 4: Verify artifact isolation: Prompt v2 never returned artifact of Prompt v1
    assert res_v1.output_data["text"] != res_v2.output_data["text"]
    assert params_v1.prompt_version == "1.0.0"
    assert params_v2.prompt_version == "2.0.0"
