#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""generate_template_aliases.py — Generates deterministic runtime template aliases.

Derives the mapping from authoritative ground-truth metadata (template_catalog.json)
and physical component implementations to canonical IDs in TEMPLATE_REGISTRY.
Zero manual maintenance. Exit 0 on success (or up-to-date in --check mode).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "ground-truth" / "template_catalog.json"
REGISTRY_FILE = ROOT / "registry" / "template-registry.tsx"
OUTPUT_ALIASES_FILE = ROOT / "registry" / "template-aliases.ts"


def generate_aliases():
    if not CATALOG_PATH.exists():
        raise FileNotFoundError(f"Missing {CATALOG_PATH}")
    if not REGISTRY_FILE.exists():
        raise FileNotFoundError(f"Missing {REGISTRY_FILE}")

    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    reg_text = REGISTRY_FILE.read_text(encoding="utf-8")

    # Extract direct canonical entries: id -> ComponentName
    pattern = r'["\']([a-zA-Z0-9_-]+)["\']:\s*\{.*?component:\s*(\w+)'
    direct_entries = dict(re.findall(pattern, reg_text, re.DOTALL))
    comp_to_canonical = {comp: key for key, comp in direct_entries.items()}

    # Filter active production templates under templates/ (exclude non-component files)
    active_templates = [
        c for c in catalog
        if c.get("path", "").startswith("templates/")
        and c.get("path") != "templates/brand-resolver.ts"
        and not c.get("path", "").endswith(".d.ts")
        and not c.get("path", "").startswith("templates/custom/")
        and c.get("path") != "templates/effects/engine-bridge.tsx"
    ]

    aliases = {}
    for item in sorted(active_templates, key=lambda x: x["name"].lower()):
        stem = Path(item["path"]).stem
        gt_name = item["name"]
        canonical_id = comp_to_canonical.get(stem)

        if not canonical_id:
            raise ValueError(f"Component '{stem}' ({item['path']}) not found in TEMPLATE_REGISTRY!")

        # Verify implementation file exists on disk
        impl_path = ROOT / item["path"]
        if not impl_path.exists():
            raise FileNotFoundError(f"Implementation file missing on disk: {impl_path}")

        # 1. Ground Truth name (e.g. Herodeviceassemblewrapper -> rui-hero-device-assemble)
        if gt_name != canonical_id:
            aliases[gt_name] = canonical_id

        # 2. PascalCase component stem (e.g. HeroDeviceAssembleWrapper -> rui-hero-device-assemble)
        if stem != canonical_id:
            aliases[stem] = canonical_id

    # Format TypeScript file
    lines = [
        "// AUTO-GENERATED by scripts/generate_template_aliases.py — DO NOT EDIT BY HAND",
        "// Authoritative alias mapping from Ground Truth (TEMPLATE_INDEX / template_catalog)",
        "// and component stems to canonical runtime TEMPLATE_REGISTRY IDs.",
        "",
        "export const TEMPLATE_ALIASES: Record<string, string> = {"
    ]

    for alias, canonical_id in sorted(aliases.items()):
        lines.append(f'  "{alias}": "{canonical_id}",')

    lines.append("};")
    lines.append("")

    return "\n".join(lines), len(active_templates), len(aliases)


def main():
    check_mode = "--check" in sys.argv

    content, active_count, alias_count = generate_aliases()

    if check_mode:
        if not OUTPUT_ALIASES_FILE.exists():
            print(f"FAIL: {OUTPUT_ALIASES_FILE} does not exist.")
            sys.exit(1)
        current = OUTPUT_ALIASES_FILE.read_text(encoding="utf-8")
        if current.strip() != content.strip():
            print(f"FAIL: {OUTPUT_ALIASES_FILE} is out of date with ground truth. Run scripts/generate_template_aliases.py to update.")
            sys.exit(1)
        print(f"PASS: {OUTPUT_ALIASES_FILE} is consistent with ground truth ({active_count} active templates, {alias_count} aliases).")
        sys.exit(0)

    OUTPUT_ALIASES_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_ALIASES_FILE.relative_to(ROOT)} ({active_count} active templates, {alias_count} aliases).")


if __name__ == "__main__":
    main()
